### ISSUE TITLE
Is it possible to remove the Press  ? for help?

### ISSUE THREAD

**Issue by computersarecool** [jaypei/emacs-neotree#101]
The title pretty much answers it - wondering if there is a way I can disable this?
Also, is it possible to resize the tray?

**Comment by sebastiencs** [comment]
You can disable it by setting neo-show-header to nil

**Comment by computersarecool** [comment]
This did not work for me.  I also tried `(setq neo-show header nil) in my .emacs and it did not work....

**Comment by jaypei** [comment]
I think you are right, there should be more efficient without banner.
Thanks for the advice.

**Comment by computersarecool** [comment]
I am not sure why this issue was closed. Unfortunately setting `(setq neo-show header nil)` in my `init.el` file does not make any change.  Anything else I can try?

**Comment by jaypei** [comment]
Hi computersarecool, 

NeoTree has been removed header without any configuration.
You can update the latest version from MELPA.

**Comment by jojojames** [comment]
Is there a way to quickly access the hotkeys for neotree? That's where I would've assumed the help ("?") to lead.

**Comment by jianingy** [comment]
I believe press "?" in neotree buffer do give a shortcuts introduction.

**Comment by jojojames** [comment]
You're right. Didn't realize Normal Mode in Evil was blocking the ? command.
