### ISSUE TITLE
Feature: resize width

### ISSUE THREAD

**Issue by jamieorc** [jaypei/emacs-neotree#103]
I'd like to be able to resize, but there's a fixed width set on the pane.

**Comment by ysgard** [comment]
+1 - not being able to resize is annoying when filenames are long or directories are deeply nested.

**Comment by dmitryanufriev** [comment]
+1

**Comment by colorgmi** [comment]
When I adjust to drag neotree size; then click to open some file; neotree window size will be reset, how to disable this behaviour?

**Comment by thinkhuman** [comment]
Can't the fixed width be overriden with `(setq neo-window-fixed-size nil) `?
