### ISSUE TITLE
'wrong type argument listp' error after the last update when enabling vc integration

### ISSUE THREAD

**Issue by kaushalmodi** [jaypei/emacs-neotree#105]
Hi,

I started getting this 'wrong type argument listp' error if I enable the vc integration feature.

I added the below to my emacs init.

```el
(setq neo-vc-integration t)
```

After that, whenever I do `neotree-toggle`, I get this error and the neotree window doesn't show any content except for the current dir name.

Here is the full error backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument listp t)
  neo-buffer--insert-dir-entry("c:/Users/Kaushal/Dropbox/home/.emacs.d/auto-save-list" 1 nil)
  neo-buffer--insert-tree("c:/Users/Kaushal/Dropbox/home/.emacs.d" 1)
  neo-buffer--refresh(nil)
  neo-buffer--change-root("c:/Users/Kaushal/Dropbox/home/.emacs.d")
  neo-global--open-dir("c:/Users/Kaushal/Dropbox/home/.emacs.d")
  neo-global--open-and-find("c:/Users/Kaushal/Dropbox/home/.emacs.d/init.el")
  neotree-find()
  neotree-show()
  neotree-toggle()
  #<subr call-interactively>(neotree-toggle nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> neotree-toggle)
  apply(ad-Advice-call-interactively #<subr call-interactively> neotree-toggle)
  call-interactively(neotree-toggle)
  (progn (setq this-command (quote neotree-toggle)) (call-interactively (function neotree-toggle)))
  hydra-launch/neotree-toggle-and-exit()
  #<subr call-interactively>(hydra-launch/neotree-toggle-and-exit nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> hydra-launch/neotree-toggle-and-exit nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (hydra-launch/neotree-toggle-and-exit nil nil))
  call-interactively(hydra-launch/neotree-toggle-and-exit nil nil)
  command-execute(hydra-launch/neotree-toggle-and-exit)
```

**Comment by jaypei** [comment]
Hi kaushalmodi,

The value type is not bool. 
```
(custom-set-variables
 '(neo-vc-integration (quote (face))))
```

:)

**Comment by kaushalmodi** [comment]
Thanks.

I actually read just the var docstring (that the value should be non-nil to show VC status) and missed reading the suggested values under `:type`

```el
(defcustom neo-vc-integration nil
  "If non-nil, show VC status."
  :group 'neotree-vc
  :type '(set (const :tag "Use different faces" face)
              (const :tag "Use different characters" char)))
```

So as per your suggestion, I did

```el
(setq neo-vc-integration '(face))
```

and that made that error to go away but I do not see the neo-vc-* faces being applied.

So I tried,

```el
(setq neo-vc-integration '(char))
```

But that gives another error:

> neo-buffer--insert-file-entry: Wrong type argument: characterp, char

**Comment by jaypei** [comment]
This error has been fixed in https://github.com/jaypei/emacs-neotree/commit/2aa69451b615d58e8afcaaa449ee9f1852d0868f .

**Comment by kaushalmodi** [comment]
That fixed the errors, but still I don't see any git info in the neotree buffer inspite of having the below in my emacs init.

```el
(setq neo-vc-integration '(face char))
```

**Comment by kaushalmodi** [comment]
I did some minor debug.

For an edited file, if I eval `(vc-state-refresh (buffer-file-name) 'Git)`, it returned `edited`. But inside the `neo-vc-for-node` fn, the `vc-state` is always `up-to-date` for all files (edited or not).

**Comment by kaushalmodi** [comment]
Finally, this modification seems to work fine for me

```el
(defun neo-vc-for-node (node)
  (let* ((backend (vc-backend node))
         (vc-state nil)
         (vc-state (when backend (vc-state node backend)))) ; I did not care about the 'user vc-state
    ;; (message "%s %s %s" node backend vc-state)
    (cons (cdr (assoc vc-state neo-vc-state-char-alist))
          (cl-case vc-state
            (up-to-date       neo-vc-up-to-date-face)
            (edited           neo-vc-edited-face)
            (needs-update     neo-vc-needs-update-face)
            (needs-merge      neo-vc-needs-merge-face)
            (unlocked-changes neo-vc-unlocked-changes-face)
            (added            neo-vc-added-face)
            (removed          neo-vc-removed-face)
            (conflict         neo-vc-conflict-face)
            (missing          neo-vc-missing-face)
            (ignored          neo-vc-ignored-face)
            (unregistered     neo-vc-unregistered-face)
            (user             neo-vc-user-face)
            (t                neo-vc-default-face))))) ; is `otherwise' a valid default condition? I changed that to `t'
```

**Comment by kaushalmodi** [comment]
For some reason `(vc-state-refresh node backend)` worked fine when evalled manually on a buffer; but it always returned `up-to-date` from within that function.

Changing that to `(vc-state node backend)` fixed that problem.

I am running emacs built from master branch.

**Comment by kaushalmodi** [comment]
I'd like to add that while my modified version above works, it is not consistent. It correctly updates the vc-status only for the file I am visiting. But the status of a file I am not visiting **might** be incorrect. I need to understand more about the operation of the `vc-status` function.. or file an emacs bug report?

**Comment by jaypei** [comment]
My test result is same as yours.

Thanks
