### ISSUE TITLE
Feature request: Contraction of singleton directory trees

### ISSUE THREAD

**Issue by milliburn** [jaypei/emacs-neotree#107]
It would be a great addition in width-constrained situations to have a directory tree such as
```
src/
  main/
    package/
      contents/
      file.scala
      file2.scala
```
automatically contract to
```
src/main/package/
  contents/
  file.scala
  file2.scala
```
assuming the `src` and `main` directories only contain one directory and no files (after filtering with `Neo Hidden Regexp List`). The implicit paths could have a special face.

The advantages would be quicker navigation, the directory structure being more obvious, and indentation not accumulating unnecessarily (although as an added bonus the indentation width itself could be adjustable).

In my use-case, I can divide 1920 pixels to 3×80-column windows leaving the NeoTree window at a width of 20 columns -- but the projects follow the Maven structure, so the tree is already really deep before any actual files are seen (and Emacs isn't the most convenient when it comes to horizontal scrolling).

GitHub's online tree browser has this capability, and the `project-explorer` package is an example implementation of this feature.

**Comment by jaypei** [comment]
Hi milliburn,

I'm sorry so late reply to you.
Your suggestion is very helpful.
I will add this feature.

Merge issue #147 .

Jay
