### ISSUE TITLE
how to hide files node?

### ISSUE THREAD

**Issue by QiangF** [jaypei/emacs-neotree#113]
Hello everyone,
When one sub folder is expanded, files in it fills up the buffer and blocks folders below. How do I show folders only?
Thank you!

**Comment by jaypei** [comment]
I think you can press `s` (neotree-select-next-sibling-node) to find the next sibling node.

Jay

**Comment by QiangF** [comment]
Thank you Jay, it works well.

**Comment by jaypei** [comment]
You are welcome :)
