### ISSUE TITLE
Add a copy command

### ISSUE THREAD

**Issue by carlesso** [jaypei/emacs-neotree#114]
Would be nice to have a copy command (like `c` in nerdtree). What do you think?

**Comment by jaypei** [comment]
Hi carlesso,

Now you can use `C-c C-p` to copy nodes. 
Thanks to @rzetterberg . :) .

**Comment by ninrod** [comment]
Ok but how do I paste?

**Comment by prassee** [comment]
how do we paste

**Comment by aborn** [comment]
@prassee Use M-x neotree-copy-node
