### ISSUE TITLE
Show hidden files by default

### ISSUE THREAD

**Issue by melihovv** [jaypei/emacs-neotree#117]
Hello, it there any setting to show hidden files by default? It is quite annoying to always press `h` to show hidden files.

**Comment by jaypei** [comment]
neo-show-hidden-files

You can use `M-x customize` to find options.

**Comment by melihovv** [comment]
Thanks! 
I use emacs since yesterday, i'm quite noobie))
If anybody wants to do the same, simply add `(setq-default neo-show-hidden-files t)` to your init.el.

**Comment by jaypei** [comment]
You are welcome. :)
