### ISSUE TITLE
How to show dot files

### ISSUE THREAD

**Issue by computersarecool** [jaypei/emacs-neotree#119]
Currently neotree does not show my dot files. Is there a way to enable this ability?

**Comment by lexi-lambda** [comment]
Does `neotree-hidden-file-toggle` do what you want?

**Comment by jaypei** [comment]
Has the answer solved your problem? @computersarecool

**Comment by computersarecool** [comment]
Yes. The new updates fixed it. Thank you

**Comment by jaypei** [comment]
You are welcome :)
