### ISSUE TITLE
"Wrong number of arguments: window-frame, 0" on emacs 24.3

### ISSUE THREAD

**Issue by bmag** [jaypei/emacs-neotree#125]
Using emacs 24.3, with `(setq neo-modern-sidebar t)`, calling `M-x neotree` shows an error: `Wrong number of arguments: window-frame, 0`. Looking at the doc for `window-frame`, in emacs 24.3 it takes a mandatory WINDOW argument, but in emacs 24.5 that argument is optional.

**Comment by jaypei** [comment]
Thanks!
