### ISSUE TITLE
Latest versions are very slow

### ISSUE THREAD

**Issue by synic** [jaypei/emacs-neotree#126]
I've updated to the latest git, and it seems there's something new that's causing some lag when opening and closing nodes, and searching.

**Comment by jaypei** [comment]
Hi synic,

Is there any message in the "*Message*" buffer?

**Comment by synic** [comment]
Unfortunately, no.  It seems to have been whatever change was on the 5th.

**Comment by synic** [comment]
Yeah, definitely something wonky.  Maybe just a spacemacs itself issue?  I feel like you would notice it right away if it was affecting you.  It takes 2-3 seconds just to expand a directory that only has 10 files in it.

**Comment by synic** [comment]
More Info:  It doesn't seem to happen to every directory.  It seems to happen to directories under git source control, that have a lot of history.

If I close emacs, `rm -rf .git` and go back to that directory, it is very fast again.

**Comment by synic** [comment]
Sorry for the bug spam here.  I've got steps to reproduce:

```bash
$ git clone git@github.com:emacs-mirror/emacs.git
```

Then, navigate to the new emacs directory in NeoTree, and try expanding the first directory, `admin`.  There should be some significant lag.

I'm on a MacBook Pro running Yosemite, using `https://github.com/railwaycat/emacs-mac-port` from homebrew.

**Comment by synic** [comment]
Really really sorry for the spam.

It appears to be the combination of `neotree` and `helm-projectile`.  If I install only these on vanilla emacs, the problem occurs.

**Comment by jaypei** [comment]
Sorry, according to your method, I still cannot recurrence the problem, are you enable the option 'neo-vc-integration'?

**Comment by synic** [comment]
Yes, that is the problem.  If set `neo-vc-integration` to `nil`, it is fast again.

Is there any way to speed that up?

**Comment by jaypei** [comment]
Yes, this feature is indeed slow, so it is closed by default.
It can speed up when NeoTree support the sub-tree refresh feature.

**Comment by razum2um** [comment]
thanks for `(setq neo-vc-integration nil)` 
it should be mentioned in README, what do you think?

**Comment by mmlac** [comment]
I don't think this issue is fixed. A simple single i.e. git status should be enough to update the full tree, and it is not bound to the history of the project.

Is there a way to optimize the feature to be usable? At the current state it does more harm than good in any even medium sized projects.

**Comment by palikar** [comment]
I don't think the bug is in recent versions of neotree. I've just tested the VC integration everything works smoothly.

**Comment by love2dishtech** [comment]
Since the bug is closed, has this been fixed. Documentation still points it is a problem.

**Comment by rubynho** [comment]
Any update on this issue?
