### ISSUE TITLE
图标样式

### ISSUE THREAD

**Issue by transtone** [jaypei/emacs-neotree#127]
默认的xpm图片实在难看，而且在高分屏下不知道怎么放大，一看sublime和atom的文件管理器，真叫漂亮。
突然想到，现在 fonticon 如此流行，可否用字体图标的方式让 neotree 更好看些呢？在emacs下是可以显示fonticon的，powerline不就是这么做的吗。这里还有个项目：https://github.com/syohex/emacs-fontawesome 。希望能看到更漂亮的 neotree

**Comment by transtone** [comment]
还有这个可以参考，Using Font Awesome in the Emacs mode line： https://gist.github.com/arnested/afd421c89a68b874e1c0

**Comment by jaypei** [comment]
这个很赞，我尝试一下，多谢：）

**Comment by aborn** [comment]
In new version's neotree, the icons theme use https://github.com/domtronn/all-the-icons.el, which looks more beautiful in GUI (only in GUI).
