### ISSUE TITLE
color settings

### ISSUE THREAD

**Issue by transtone** [jaypei/emacs-neotree#130]
light theme下颜色(图标)如何自定义，可否写在文档里？
不会配，丑哭了。
![image 2](https://cloud.githubusercontent.com/assets/46688/10090649/82ed4f6e-6364-11e5-9802-f639d356ff68.png)

**Comment by jaypei** [comment]
现在还不支持自定义图标，这个我想办法解决。
现在想定义的话，可以重写 neo-buffer--get-icon 的实现。

**Comment by transtone** [comment]
其实这里说的不是要换图标，不是有4种（classic，ascii，arrow，nerd）显示方式吗，怎么设置？另外dir的颜色，file的颜色也是可以设置的吧。 

看不懂lisp代码，源码的头部注释里也只写了如何引用，没写如何设置。

**Comment by jaypei** [comment]
有个简单的办法，M-x customize，搜索 NeoTree，修改完以后点 Apply and Save 就能在自己的 custom.el 里找到定义的方法了。
