### ISSUE TITLE
Neotree inhibits balance-windows

### ISSUE THREAD

**Issue by TheBB** [jaypei/emacs-neotree#132]
Is there any way to have a fixed-size neotree open, but where `M-x balance-windows` can still resize the *other* windows?

**Comment by synic** [comment]
Hey @jaypei, you there?

**Comment by jaypei** [comment]
Hi TheBB,

The implementation of balance-windows is horizontal balance and vertical balance,
the trigger condition of these is the "window--resize-apply-p" function return t.
By default, NeoTree window width is locked by using window-size-fixed, so the horizontal balance is ignored.

I will solve this issue ASAP.

jaypei
