### ISSUE TITLE
neotree is very slow

### ISSUE THREAD

**Issue by svalaskevicius** [jaypei/emacs-neotree#133]
hi, after an udpate ~13d ago neotree became very slow, especially unusable when a directory has many files..

**Comment by synic** [comment]
Might be a duplicate of https://github.com/jaypei/emacs-neotree/issues/126

**Comment by svalaskevicius** [comment]
yepp, it is - added `(setq neo-vc-integration nil)` and its fast again - thanks!

**Comment by YangJie6020** [comment]
> yepp, it is - added `(setq neo-vc-integration nil)` and its fast again - thanks!

That sloves my problem, Tks!!
