### ISSUE TITLE
How to order the directory by name in neotree buffer?

### ISSUE THREAD

**Issue by jasondf** [jaypei/emacs-neotree#134]
It seems ordered by created time now, how to change it by names?
<img width="706" alt="screen shot 2015-10-12 at 13 21 48" src="https://cloud.githubusercontent.com/assets/9963736/10421907/764a8226-70e4-11e5-9a2c-c102d91da845.png">

**Comment by jaypei** [comment]
Hi jasondf,

There is only one implementation now, sort by name.
You can add an advice function by `neo-buffer--get-nodes`.

Jay

**Comment by jasondf** [comment]
Oh, I'm a beginner, see what I can do about this, thanks.

**Comment by jaypei** [comment]
Sorry, I misunderstood your question.
The order of directory have been sorted by name.
In your case, upper-case first, and then lower-case.

Jay

**Comment by jasondf** [comment]
Hi Jay,
How to make the sort to be case insensitive then?

**Comment by jaypei** [comment]
For example,

```elisp
(defadvice neo-buffer--get-nodes
    (after neo-buffer--get-nodes-new-sorter activate)
  (setq ad-return-value
        (let ((nodes ad-return-value)
              (comparator (lambda (s1 s2) (string< (downcase s1)
                                              (downcase s2)))))
          (apply 'cons (mapcar (lambda (x) (sort (apply x (list nodes))
                                            'comparator))
                               '(car cdr))))))

```

**Comment by jasondf** [comment]
Hi Jay,
After I loaded those code above, neotree list nothing but a "up a dir" link ...

**Comment by jasondf** [comment]
Oh, I check the code again, change 'comparator to comparator, and now it works.
Thanks a lot.

**Comment by jaypei** [comment]
You are welcome.

**Comment by tobimensch** [comment]
I modified it to sort by file extensions as well:

**Comment by jvillasante** [comment]
Is it possible to also get "natural order" sorting?

For example:
```
1
2
10
```

Right now we get:
```
1
10
2
```

**Comment by zaen323** [comment]
@jvillasante I too wonder if that's possible.
