### ISSUE TITLE
How to enable default filtering?

### ISSUE THREAD

**Issue by jluttine** [jaypei/emacs-neotree#141]
I noticed it is possible to filter filenames:
https://github.com/jaypei/emacs-neotree/issues/53

And if I understand correctly, Neotree should filter filenames ending in `~` by default, right?
https://github.com/jaypei/emacs-neotree/blob/cd02617453a0a780bc8fa13efb2426f1623cfd4d/neotree.el#L262

However, I'm using develop branch version but still `filename.py~` files are shown in Neotree. Any advice how I can fix this? Do I need to enable the filtering somehow? I couldn't find any documentation about this, so I thought I'd ask here.

I'm using Spacemacs, if that makes any difference.

**Comment by jaypei** [comment]
Hi jluttine,

Yes, by default it should not be showed.
You can use this command to check whether or not the rules were changed:
C-h v neo-hidden-regexp-list RET

Jay

**Comment by palikar** [comment]
@jluttine do you still have the problem or can I close the issue?

**Comment by palikar** [comment]
Hey @jluttine do you still have the problem or can I close the issue?

**Comment by jluttine** [comment]
I ran the command Jay gave and the result was:
```
neo-hidden-regexp-list is a variable defined in ‘neotree.el’.
Its value is ("^\\." "\\.pyc$" "~$" "^#.*#$" "\\.elc$")

Documentation:
*The regexp list matching hidden files.

You can customize this variable.
```

I still see files ending in `~` in neotree. `"~$"` regexp should have hide those, right? If so, then the problems still exists.

**Comment by palikar** [comment]
Thanks for the response @jluttine . I just tried it out and with the latest version of neotree (on the dev branch) everything works as expected. `~$` is in the list by default. Be sure to toggle the hidden files in the neotree buffer with `H`. The following screenshots illustrate what I observer in the latest neotree.

Hidden files on:
![screenshot from 2018-11-14 10-50-25](https://user-images.githubusercontent.com/11386449/48474589-24805d80-e7fb-11e8-9df9-8edc5397934d.png)


Hidden files off:
![screenshot from 2018-11-14 10-46-20](https://user-images.githubusercontent.com/11386449/48474494-f69b1900-e7fa-11e8-923b-d68f77514b3e.png)

**Comment by jluttine** [comment]
Yes, that hidden files on/off apparently was what I needed. I toggled them off and now the filter is applied. Thanks! I hadn't known about that. (In Spacemacs this toggling is binded to key `s`, in case some other Spacemacs user happens to wonder.)
