### ISSUE TITLE
Neotree forces adjacent window down when opening directory

### ISSUE THREAD

**Issue by angrygoats** [jaypei/emacs-neotree#143]
Hello,

I have had this problem for a while and I dont know what causes it. 
![screen shot 2015-12-04 at 11 55 29 am](https://cloud.githubusercontent.com/assets/11184919/11599868/1f2a599e-9a7e-11e5-9a22-0f25c382cb57.png)

You can see here I have my `init.el` opened, and I try to open the `eshell` directory and it clearly pushes the adjacent window down. 

My init.el is available [here](https://github.com/angrygoats/essentials/blob/master/dotfiles/emacs.d/init.el). I would really appreciate this being solved, it is very annoying while working. I'm sure its something I did wrong, I'm just not sure where. Thanks!

**Comment by jaypei** [comment]
Hi angrygoats,

I was not able to recurred the problem using your config file.
I suggest you try to disable the auto-complete to see if it resolves on its own.
What version of emacs are you using?

Jay

**Comment by palikar** [comment]
Hi @angrygoats  do you still have the problem or can I close the issue?
