### ISSUE TITLE
VC mode display error

### ISSUE THREAD

**Issue by s3bs** [jaypei/emacs-neotree#144]
I get the following error when using neotree. Where `<filename>` is an actual full path to a filename.

`The following vc-responsible-backend: No VC backend is responsible for <filename>`

My root sits in a CVS repository but the subfolder has not been added to the repository yet, so there is no vc backend responsible for it. Hence the above error. 
In `neo-vc-for-node` neotree calls `vc-state` which will throw an error if the backend is nil. Please don't use the function `vc-state` if there is no backend according to `vc-backend` or catch the error. 
I'm using Emacs25.

**Comment by anmonteiro** [comment]
+1

**Comment by jaypei** [comment]
Fixed, thanks!
