### ISSUE TITLE
Rename issure

### ISSUE THREAD

**Issue by jasondf** [jaypei/emacs-neotree#145]
First I created a file: admin.java,  then realized it should be "Admin.java". So I press C-c C-r and input "Admin.java" to rename it. But minibuffer show a message "File already exists", and the file name remain unchanged. Is that a bug?

**Comment by jaypei** [comment]
Are  you using Emacs in Windows?

**Comment by jasondf** [comment]
Well, I use Emacs 24.5 on Mac OSX 10.11.

**Comment by jaypei** [comment]
Hi jasondf,

Sorry, I have no Mac OS to test it.
But I think the results should be consistent with Linux.
Can you test this statement in your environment?

(rename-file "/path/to/admin.java" "/path/to/Admin.java")


Jay

**Comment by jasondf** [comment]
Hi Jay,
I tested the rename-file statement, Emacs feedback that the file already exists, need make confirm for the rename operation, and then it works. 
And still C-c C-r won't work correctly.

**Comment by syohex** [comment]
MacOSX uses case insensitive file system. So `admin.java` is equal to `Admin.java`, `AdMIN.java` etc.

**Comment by jaypei** [comment]
You are right, thanks @syohex 

http://apple.stackexchange.com/questions/71357/how-to-check-if-my-hd-is-case-sensitive-or-not

**Comment by syohex** [comment]
How about passing third argument of `rename-file` ? `rename-file` document says as below.

> A number as third arg means request confirmation if NEWNAME already exists.

Patch is here.

```diff
diff --git a/neotree.el b/neotree.el
index 66163ce..25a123d 100644
--- a/neotree.el
+++ b/neotree.el
@@ -1414,7 +1414,7 @@ If there is no button in current line, then return DEFAULT."
       (if buffer
           (with-current-buffer buffer
             (set-visited-file-name to-path nil t)))
-      (rename-file current-path to-path)
+      (rename-file current-path to-path 1)
       (neo-buffer--refresh t)
       (message "Rename successful."))))
```

**Comment by jasondf** [comment]
Thanks syohex, it works now, hohoho
