### ISSUE TITLE
view file without "enter"

### ISSUE THREAD

**Issue by xin-jin** [jaypei/emacs-neotree#148]
It there a way to just view a file without "entering" it, like `direx:display-item`? Often I just want to quickly browse through files.

**Comment by voland62** [comment]
+1.
Need this...

**Comment by aborn** [comment]
Please try the latest version. Function `neotree-quick-look` (binding to hot-key **SPC**) finished this feature.

**Comment by xin-jin** [comment]
It does work. Thanks!
