### ISSUE TITLE
Toggle neotree with Projectile root

### ISSUE THREAD

**Issue by xin-jin** [jaypei/emacs-neotree#149]
Hi,

Is it possible to toggle neotree at projectile root? 

For example, currently when I toggle neotree at a file in a subdirectory of the project:
![selection_001](https://cloud.githubusercontent.com/assets/6195346/12344396/606c7b9c-baf1-11e5-9c64-d71d9d44c66f.png)

My desired behavior would be like this:
![selection_002](https://cloud.githubusercontent.com/assets/6195346/12344404/737c63a0-baf1-11e5-9f08-db4ec0198765.png)

I searched in the issues, and it seems that this kind of function has been implemented. But somehow it does not work anymore now.

Thanks!

**Comment by gdkrmr** [comment]
`M-x neotree-projectile-action` works for me

**Comment by xin-jin** [comment]
@gdkrmr hi, but it doesn't point to the file I am currently editing.

**Comment by xakz** [comment]
I use that, binded it to F2
```elisp
(defun neotree-project-root-dir-or-current-dir ()
  "Open NeoTree using the project root, using projectile, or the
current buffer directory."
  (interactive)
  (let ((project-dir (ignore-errors (projectile-project-root)))
        (file-name (buffer-file-name))
        (neo-smart-open t))
    (if (neo-global--window-exists-p)
        (neotree-hide)
      (progn
        (neotree-show)
        (if project-dir
            (neotree-dir project-dir))
        (if file-name
            (neotree-find file-name))))))
```

**Comment by ideasman42** [comment]
@xakz, note that this script fails (for me at least), if `neotree` isn't yet activated. I needed to check that `neo-global--window-exists-p` is defined. eg:

    (defun neotree-project-dir-toggle ()
      "Open NeoTree using the project root, using find-file-in-project,
    or the current buffer directory."
      (interactive)
      (let ((project-dir
             (ignore-errors
               ;;; Pick one: projectile or find-file-in-project
               ; (projectile-project-root)
               (ffip-project-root)
               ))
            (file-name (buffer-file-name))
            (neo-smart-open t))
        (if (and (fboundp 'neo-global--window-exists-p)
                 (neo-global--window-exists-p))
            (neotree-hide)
          (progn
            (neotree-show)
            (if project-dir
                (neotree-dir project-dir))
            (if file-name
                (neotree-find file-name))))))

**Comment by xakz** [comment]
@ideasman42 , thank for the advice, I will add it after my holidays. Merry chrismas :-)
