### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ReneFroger** [jaypei/emacs-neotree#150]
Hi there! 

I noticed there are many issues without any reply for months. So I began to wonder if this project is still maintained? If not, are you interest to hand down this project to another fork with a new maintainer?

**Comment by jaypei** [comment]
Hi ReneFroger,

I am a little busy these months, I'm sorry about that.

I would like to continue to maintain the project.
I will improve performance problems and release a new version recently.

If I decided to give up the project, I'll looking a new maintainer.

Thank you for your concern on the project.


Jay

**Comment by ReneFroger** [comment]
Please let me know if you're looking for a new maintainer.

**Comment by jaypei** [comment]
OK.
Do you want to maintain this project with me?

Jay

**Comment by aborn** [comment]
@jaypei 
Can you add me as collaborator. I would like to do some fix bug work and as maintainer.
