### ISSUE TITLE
"modern sidebar" not working

### ISSUE THREAD

**Issue by jrab89** [jaypei/emacs-neotree#151]
With version `20160111.2358` of neotree from melpa:

![modern_sidebar_broken](https://cloud.githubusercontent.com/assets/3112565/12771298/ef25252c-c9ed-11e5-9183-c21157dfb383.gif)

Using [6d5b1a0](https://github.com/jaypei/emacs-neotree/blob/6d5b1a0efa2881d41f159052fa692342ca3d7edb/neotree.el):

![modern_sidebar_works](https://cloud.githubusercontent.com/assets/3112565/12771352/50093f86-c9ee-11e5-99ac-49e9ba870ba2.gif)

Here is my neotree related configuration:

```elisp
(setq-default neo-keymap-style 'concise)
(require 'neotree)
(setq
  neo-show-hidden-files t
  neo-modern-sidebar nil
  neo-dont-be-alone t
  neo-banner-message nil
  neo-create-file-auto-open t
  neo-persist-show nil
  neo-smart-open t)
```

Thanks!

**Comment by jaypei** [comment]
Thanks
