### ISSUE TITLE
Symbol's function definition is void: vc-responsible-backend

### ISSUE THREAD

**Issue by anmonteiro** [jaypei/emacs-neotree#153]
Latest package throws this error:

`neo-vc-for-node: Symbol's function definition is void: vc-responsible-backend [3 times]`

**Comment by syohex** [comment]
vc.el has to be loaded for using `vc-responsible-backend` on older Emacs(`(require 'vc)`). While it is autoloaded function on newer Emacs like Emacs 25.

You can fix this issue by `(require 'vc)`.

**Comment by anmonteiro** [comment]
@syohex that fixes it, thanks!
