### ISSUE TITLE
Question: automatically run neotree-dir when in go-mode?

### ISSUE THREAD

**Issue by tleyden** [jaypei/emacs-neotree#155]
Thanks for creating emacs-neotree! 

How can I set things up so that whenever I'm in `go-mode` that it will run `M-x neotree-dir` and display a directory sidebar to show the contents of the current directory I'm in?

**Comment by jaypei** [comment]
Hi tleyden,

You are welcome.
I guess you want to open neotree automatically when open a golang file.
If so, you can try this code:

```elisp
(add-hook 'go-mode-hook
          (lambda nil (save-excursion (neotree-show))))
```


Jay
