### ISSUE TITLE
"Wrong number of arguments: window-frame, 0" on emacs 24.3

### ISSUE THREAD

**Issue by lebedov** [jaypei/emacs-neotree#162]
I noticed that this problem was reported in the past (#125) and fixed, but it seems that ``neo-global--create-window`` is calling ``window-frame`` without an argument in MELPA release 20150214.532.

**Comment by syohex** [comment]
NOTE: Its changes was reverted at https://github.com/jaypei/emacs-neotree/commit/2601170ed48f90af76adf31dd579a6ccf0273308

**Comment by jaypei** [comment]
Hi lebedov,

Yes, just upgrade.
Have you solved the problem?

Jay

**Comment by lebedov** [comment]
Upgrade to what? ``window-frame`` is [still called without an argument](https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el#L628) in the latest revision (3d1c0ad) on GitHub; shouldn't that line be updated?

**Comment by jaypei** [comment]
Sorry, I misunderstood you mean. That's a bug again. I think need to find a way to test this version in CI.

**Comment by lebedov** [comment]
Thanks!

**Comment by jaypei** [comment]
You are welcome.
