### ISSUE TITLE
Automatically open NeoTree on Emacs startup

### ISSUE THREAD

**Issue by fusion809** [jaypei/emacs-neotree#164]
Hi,

I was wondering if I can get NeoTree to automatically open on Emacs startup. I have tried adding:

``` lisp
(require 'neotree)
(neotree-mode t)
```

to my init file, in my case `~/.spacemacs` as I am using the Spacemacs mode, but this returned errors on startup. So how do I get NeoTree to automatically open up in the present working directory being used by Emacs (which by default is my home folder `~/`), whenever Emacs is started? I know how to toggle NeoTree by pressing the <kbd>F8</kbd> key, once Emacs is running, by adding:

``` lisp
(global-set-key [f8] 'neotree-toggle)
```

to my init file, but how do I get NeoTree to be toggled automatically on Emacs startup? 

Thanks for your time,
Brenton

**Comment by jianingy** [comment]
try this, 
```elisp
(neotree-toggle)
(neotree-dir "~/devel")
(switch-to-buffer-other-window "*scratch*")
```

**Comment by chris-martin** [comment]
I'm confused, how does that address the problem? Why switch to `~/devel` (where did that directory come from)? Why open the scratch buffer?

**Comment by jojojames** [comment]
(add-hook 'after-init-hook #'neotree-toggle)

**Comment by idf** [comment]
@jojojames But it does not work well with emacsclient.

**Comment by jojojames** [comment]
@idf 
You can probably combine that with 'server-visit-hook. I haven't tried it myself since I lazy load neotree.

https://stackoverflow.com/questions/1040143/how-to-automatically-evaluate-certain-lisp-code-after-starting-an-emacsclient

**Comment by idf** [comment]
Thanks for your suggestion! I tried and found `server-switch-hook` works better. 
`(add-hook 'server-switch-hook (lambda () (call-interactively 'neotree-show)))`

**Comment by idf** [comment]
@jojojames 
Regarding `(add-hook 'after-init-hook #'neotree-toggle)` in normal `emacs`. Neotree open a scratch buffer. How to avoiding opening a separately scratch buffer

![screen shot 2017-02-24 at 4 43 35 pm](https://cloud.githubusercontent.com/assets/2493622/23351876/cd94aa54-fc78-11e6-90a9-6a53a51c7a4d.png)

**Comment by idf** [comment]
My two cents:
```lisp
(defun neotree-startup ()
  (interactive)
  (neotree-show)
  (call-interactively 'other-window))

(if (daemonp)
    (add-hook 'server-switch-hook #'neotree-startup)
  (add-hook 'after-init-hook #'neotree-startup)
)
```

**Comment by jojojames** [comment]
@idf That looks like you might have something else in your config loading the second window. I'd bisect your config.

**Comment by idf** [comment]
@jojojames okay. seems so. thanks for your advice.

**Comment by rawkode** [comment]
@idf I'm getting a scratch buffer too when using `after-init-hook`, please let me know if you work this out. Thanks! :+1:

**Comment by idf** [comment]
@rawkode Have you tried out the script with `neotree-startup`?

**Comment by timoxley** [comment]
None of the above suggestions worked for me using `spacemacs`, not sure why. 

This did work though:

```
;; ~/.spacemacs
;; …
(defun dotspacemacs/user-config ()
   ;; …
   (add-hook 'window-setup-hook #'neotree-find-project-root)
)
```

**Comment by Aut0matt** [comment]
i use spacemacs and for me work this:

`(defun dotspacemacs/user-config ()
   (add-hook 'window-setup-hook #'neotree-find-project-root)
)`

**Comment by palikar** [comment]
Ok, seems this issue was figured out. I will consider adding some of the snippets here to the documentation so that others can implement the behavior for themselves. Closing the issue for now.
