### ISSUE TITLE
Change focus behaviour for neotree-enter

### ISSUE THREAD

**Issue by Dapuva76** [jaypei/emacs-neotree#165]
Basically I'd like to stay in the neotree buffer, while viewing the file in the other window. I've searched around, but couldn't find anything to modify its behaviour.

**Comment by jaypei** [comment]
Hi Dapuva76,

Yes, NeoTree needs a preview feature.

Jay

**Comment by Dapuva76** [comment]
Yeah I think that's more or less the same as Ranger's preview function, which is what I had in mind.

**Comment by Abdisalan** [comment]
Looks completed, closing.
