### ISSUE TITLE
VCS integration

### ISSUE THREAD

**Issue by Crandel** [jaypei/emacs-neotree#166]
Hello, thank you for this beautiful package. It`s very useful for me after vim. But I miss one little function, exists in this [project](https://github.com/Xuyuanp/nerdtree-git-plugin). It help to see which files in directory modified. Could you implement this functionality in your package?

**Comment by jaypei** [comment]
Hi Crandel,

Have you tried the option `neo-vc-integration`?
But unlike this project,  NeoTree only can highlight files.

Jay

**Comment by Crandel** [comment]
Thank you for help. Can you add this option into documentation? I didn`t see it there

**Comment by jaypei** [comment]
OK.  You are welcome. :)

**Comment by Crandel** [comment]
Could you tell me how I can enable this function?
I add this to my init.em
```lisp
(setq neo-vc-integration t)
```
but it didn`t show any changed files in directory

**Comment by jaypei** [comment]
For examples:

```
(custom-set-variables
 '(neo-theme (quote classic))
 '(neo-smart-open t)
 '(neo-vc-integration (quote (face)))
 '(neo-fit-to-contents t)
 '(neo-cwd-line-style 'text)
 '(neo-window-position 'right))
```

M-x customize RET, and search "NeoTree",
you can see all of options about NeoTree and easy to setup them by UI.

**Comment by Crandel** [comment]
When I press M-x customize RET, and search "NeoTree" there are a few options, but nothing about vc-integration and in the end it shows 

Subgroups:                                                                                                                                               [Neotree Options]   Options for neotree.

When I pressed on it I see

Info file neotree does not exist

I installed Neotree using el-get

**Comment by jaypei** [comment]
The feature has only in the dev branch, you can install it using MELPA.

**Comment by Crandel** [comment]
Thank you very much!!! It`s work at last. I`m very happy :)

**Comment by jaypei** [comment]
:)
