### ISSUE TITLE
Eyebrowse mode incompatibility

### ISSUE THREAD

**Issue by Alexander-Miller** [jaypei/emacs-neotree#167]
To reproduce:
- Start emacs with neotree and eyebrowse-mode
- `neotree-toggle` to show neotree
- switch to a second eyebrowse workspace
- `neotree-toggle` twice to show neotree in this workspace and then close it again
- switch to original eyebrowse workspace
- switch to neotree buffer, try to enter some directory
- [A second neotree buffer opens up next to the first](http://i.imgur.com/z6Nb1Dq.png)

I'm running emacs 25.1.50.1 and the most uptodate version of neotree directly from github.

**Comment by bmag** [comment]
@Alexander-Miller Try hooking `neo-global--attach` into `eyebrowse-post-window-switch-hook`

**Comment by andreyorst** [comment]
Any update on this? I also having trouble with eyebrowse making neotree an ordinary window, which means that it gets closed with `C-w 1`.

**Comment by Alexander-Miller** [comment]
I have since written my own filetree:
https://github.com/Alexander-Miller/treemacs

I guess that counts as an update.

**Comment by andreyorst** [comment]
Yeah I'm aware of treemacs, but it is slow so I probably won't use it. I mean I can see how treemacs window content appears and items get colorized one by one.

**Comment by Alexander-Miller** [comment]
That ... is strange. And not supposed to happen. Treemacs should be as fast as dired, and a whole lot faster than neotree. You should open an issue, and include some profiler output.

**Comment by Alexander-Miller** [comment]
Wait up. Do you mean the delay of nodes getting colored according to their git status? Because that's intentional, and configurable- there's a 0.5s delay to make sure the asynchronous git process is finished before its output are used. The results are also cached, so most of the time you won't see the delay either.

**Comment by andreyorst** [comment]
> Wait up. Do you mean the delay of nodes getting colored according to their git status? Because that's intentional, and configurable- there's a 0.5s delay to make sure the asynchronous git process is finished before its output are used. The results are also cached, so most of the time you won't see the delay either.

Hm, maybe, I don't use treemacs, so I don't know what it does. When I tested it several months ago it did that. Maybe it's git. Looking through your readme tells me that this may actually be it. I'll try it again

**Comment by andreyorst** [comment]
@Alexander-Miller what I need to say is thank you for Treemacs!

**Comment by Abdisalan** [comment]
Looks like this issue is resolved
