### ISSUE TITLE
Open / Close Neotree with the same keymap

### ISSUE THREAD

**Issue by der-Daniel** [jaypei/emacs-neotree#171]
Hi,

I am used to use "C-<" to open and close the file tree.
Is there a simple way of obtaining this behavior for neotree?

So "C-<" to open, if not opened yet and vice versa?

For Frodo.

**Comment by iAmMrinal0** [comment]
@der-Daniel: Add this to your config `(global-set-key (kbd "C-<") 'neotree-toggle)`

**Comment by aborn** [comment]
Thanks @iAmMrinal0
