### ISSUE TITLE
VC integration issue

### ISSUE THREAD

**Issue by Crandel** [jaypei/emacs-neotree#172]
When I change files of add new file to repository everything good, files mark as they must be marked, but if I have unregistered files or ignored, it doesn`t show them. I try different themes, face and char  neo-vc-integration, emacs gui and console versions. vc-dir shows all variants(added, updated, ignored and unregistered files)
![noetree](https://cloud.githubusercontent.com/assets/4005032/15392206/53fa5e34-1dce-11e6-84d6-4d20d257d303.png)

**Comment by AndreaOrru** [comment]
Hi, I can reproduce this unfortunately. Any hints on what the problem might be?

**Comment by Crandel** [comment]
I have no idea, I\`m newbie in emacs(

**Comment by sw9** [comment]
I've experienced this problem as well using neotree with git repositories. The underlying issue is that vc-git-state responds with up-to-date for unregistered files. It also doesn't report when a file is ignored. To work around the first issue at least, I redefined neo-vc-for-node in my init file. Now at least, unregistered files use the neo-vc-default-face instead of the neo-vc-up-to-date-face.

`(defun neo-vc-for-node (node)
  (let* ((backend (ignore-errors
                    (vc-backend node)))
         (vc-state (when backend (vc-state node backend)))
         )
    (cons (cdr (assoc vc-state neo-vc-state-char-alist))
          (cl-case vc-state
            (up-to-date       neo-vc-up-to-date-face)
            (edited           neo-vc-edited-face)
            (needs-update     neo-vc-needs-update-face)
            (needs-merge      neo-vc-needs-merge-face)
            (unlocked-changes neo-vc-unlocked-changes-face)
            (added            neo-vc-added-face)
            (removed          neo-vc-removed-face)
            (conflict         neo-vc-conflict-face)
            (missing          neo-vc-missing-face)
            (ignored          neo-vc-ignored-face)
            (unregistered     neo-vc-unregistered-face)
            (user             neo-vc-user-face)
            (otherwise        neo-vc-default-face)))))`

**Comment by daniel-koudouna** [comment]
This is still an issue for me. @sw9 's solution is a good workaround, as I am only working with git repositories at the moment.

**Comment by Crandel** [comment]
After updating to emacs 26 the problem disappeared
