### ISSUE TITLE
Use display-buffer for better customizability

### ISSUE THREAD

**Issue by bmag** [jaypei/emacs-neotree#173]
Hi, I'm trying to make imenu-list and neotree windows both appear on the left side, with neotree above imenu-list, but I'm having a hard time because neotree doesn't use display buffer.

Theoretically, the following code is supposed to display buffers "buff1" and "buff2" on the left side of the frame, with "buff1" above "buff2":
```elisp
(push '("buff1" display-buffer-in-side-window (side . left) (slot . 1))
      display-buffer-alist)
(push '("buff2" display-buffer-in-side-window (side . left) (slot . 2))
      display-buffer-alist)
(display-buffer (get-buffer-create "buff1"))
(display-buffer (get-buffer-create "buff2"))
```

However, neotree can't be customized to use `display-buffer-in-side-window`, because it `neo-global--create-window` is hard coded to call `split-window` directly:
```elisp
(defun neo-global--create-window ()
  "Create global neotree window."
  (let ((window nil)
        (buffer (neo-global--get-buffer t))
        (window-pos (if (eq neo-window-position 'left) 'left 'right)))
    (setq window
          (select-window
           (split-window
            (frame-root-window (window-frame (selected-window)))
            nil window-pos)))
    (neo-window--init window buffer)
    (neo-global--attach)
    (neo-global--reset-width)
    window))
```

I propose to replace the call to `split-window` with:
```elisp
(display-buffer buffer neo-display-action)
```
Where `neo-display-action` is a new customizable variable, which by default is set to an action that calls `split-window` in the same way as the original `neo-global--create-window`. It shouldn't change the default behavior of neotree, but it will make it very easy to customize.

I'll try to submit a PR with the necessary changes, so it's easier to understand what I'm talking about. Do you have any objections or suggestions?

**Comment by jaypei** [comment]
Hi bmag,

This is very useful, thanks!

Jay
