### ISSUE TITLE
显示样式问题

### ISSUE THREAD

**Issue by fxbszj** [jaypei/emacs-neotree#175]
1，黑色终端下（XShell 和 secureCRT都是)，，文件名显示的也是黑色，无法正常显示，把光标移动到文件位置才能一个一个的显示字母
2，非黑色终端(gnome-terminal), 前面显示一个方框
![1](https://cloud.githubusercontent.com/assets/13925020/16409805/e52338f2-3d51-11e6-9459-e28ab78505a7.jpg)
![2](https://cloud.githubusercontent.com/assets/13925020/16409807/e9f514ea-3d51-11e6-98cd-41bfe2a1dc54.jpg)

**Comment by jaypei** [comment]
Hi fxbszj,

I guess you lost some icon files in neotree directory.

```
/path/to/neotree/icons/{open,leaf,close}.xpm
```

If so, you should reinstall neotree by MELPA.


Jay

**Comment by fxbszj** [comment]
@jaypei  Yeah， it works if I copy the 'icons' directory to the path. (The problem in the second picture)

But the problem in the first picture still exits when I use xshell or secureCRT. The words are black, and my background is black too, so I can not see them any more. 

Sorry for my poor English.

**Comment by flyingalex** [comment]
@jaypei 您好，插件很赞！！！但是在mac上即使有那几个icon文件也是显示不了文件，请问是什么问题的？插件在linux上没有这个问题，谢谢～
<img width="244" alt="2016-08-14 09 19 12" src="https://cloud.githubusercontent.com/assets/11313145/17646518/37c2c8c0-6200-11e6-8d66-3ce9b53b61eb.png">

**Comment by fxbszj** [comment]
@flyingalex  这个问题就是和我的第一问题一样了，其实不是没有显示文件，而是显示文件的颜色和背景色相同

**Comment by flyingalex** [comment]
@fxbszj ,谢谢，搞定了
