### ISSUE TITLE
How to switch window between left part and right part?

### ISSUE THREAD

**Issue by cpselvis** [jaypei/emacs-neotree#176]
I read document in Emacs Wiki(https://www.emacswiki.org/emacs/NeoTree), there are many useful commands, but I didn't find switch window command. For instance, if someone use vim and has installed neotree plugin, he can use (ctrl+w+j/k). How about emacs-neotree plugin? Could you please tell me the method? (currently, I use F8)

**Comment by jaypei** [comment]
Hi cpselvis,


I suggest using the `window-numbering`, and customize it like this:

```
(defun set-window-number-0 ()
  "Refs spacemacs."
  (defun spacemacs//window-numbering-assign (windows)
    "Custom number assignment for special buffers."
    (mapc (lambda (w)
            (when (and (boundp 'neo-global--window)
                       (eq w neo-global--window))
              (window-numbering-assign w 0)))
          windows))
  (add-hook 'window-numbering-before-hook 'spacemacs//window-numbering-assign))

(setq window-numbering-auto-assign-0-to-minibuffer nil)

(set-window-number-0)
```

Then you can use M-1 to M-9 to switch window, and use M-0 to swith to neotree buffer.
You can also press a number key before open a file, and the file will opened in the corresponding window.


Jay

**Comment by braveoyster** [comment]
@cpselvis  I guess C-x o(other-window) was what you want.

**Comment by cpselvis** [comment]
Yes, exactly, @braveoyster   Your answer is totally to the point, thanks.
