### ISSUE TITLE
emacs file1 file2 file3 => File buffers don't use main window split

### ISSUE THREAD

**Issue by mcandre** [jaypei/emacs-neotree#177]
I want to launch neotree automatically, but when I add `(neotree)` to my `~/.emacs`, then any file arguments passed to the emacs command appear squished along the right side, failing to make use of the main window split.

**Comment by jaypei** [comment]
Hi mcandre,

I think this is caused by `set-window-dedicated`.
These two variables should be helpful.

```
(setq split-height-threshold nil)
(setq split-width-threshold nil)
(neotree)
```

Jay

**Comment by palikar** [comment]
Hi @mcandre,
have you figured it out and do you still have the problem?

**Comment by Abdisalan** [comment]
Closing as stale. If you're still experiencing this, please open a new issue.
