### ISSUE TITLE
Optionally  switch to Neotree buffer when executing `neotree-toggle`

### ISSUE THREAD

**Issue by anmonteiro** [jaypei/emacs-neotree#179]
Currently the default behavior is to switch to the Neotree buffer when executing `neotree-toggle`. 

I'd like that to be optional, i.e. open the Neotree window but remain in the current buffer I'm editing.

**Comment by aborn** [comment]
In my opinion, this is a good advice. Sometimes, we don't want to switch our current buffer to \*neotree-buffer*.

**Comment by aborn** [comment]
@anmonteiro Please try the latest version. 
`(setq neo-toggle-window-keep-p t)`

**Comment by anmonteiro** [comment]
@aborn works great, thanks!
