### ISSUE TITLE
Ignoring files independend of projectile

### ISSUE THREAD

**Issue by tobimensch** [jaypei/emacs-neotree#185]
It would be great if neotree supported one of the following:
- support for .gitignore
- support for custom ignore patterns
- ignoring files not in the git repository

**Comment by aborn** [comment]
Hi, @tobimensch you can custom ignore patterns:
`(setq neo-show-hidden-files nil)`
And the ignore patterns are determined by `neo-hidden-regexp-list`

**Comment by tobimensch** [comment]
`(defun neo-util--hidden-path-filter (node)
  "A filter function, if the NODE can not match each item in \
`neo-hidden-regexp-list', return t."
  (if (not neo-buffer--show-hidden-file-p)
      (let ((shortname (neo-path--file-short-name node)))
        ;;(if (null (neo-util--filter
        ;;       (lambda (x) (not (null (string-match-p x shortname))))
        ;;       neo-hidden-regexp-list))
               (progn
                      (if (= 0 (car (process-exit-code-and-output "git" "-C" (file-name-directory node)  "ls-files" node "--error-unmatch")))
                      node
                  )
               )
         ;;           t
         ;;      )
               )
    node))`

I rewrote neo-util--hidden-path-filter to ignore files not in the git repository. But I'm new to elisp, so this code is really hacky and less than ideal. It's slow as well and I'd like suggestions on how to make it faster. The main problem is that git has to be executed for each file.

**Comment by tobimensch** [comment]
Here's an updated version using a hash map to speed it up, but it's still hacky:

```
(defun is-in-git-repository (node)
    (setq-local val (gethash node git-hash))
    (if (equal val nil)
    (progn
    (setq-local return-value (car (process-exit-code-and-output "git" "-C" (file-name-directory node)  "ls-files" node "--error-unmatch")))
    (puthash node return-value git-hash)
    (if (= 0 return-value)
       (progn
       (puthash node t git-hash)
       t)
       (progn
       (puthash node 0 git-hash)
       nil)
    ))
    (progn
      (if (equal val 0)
         nil
         t
      )
    )
    )
)

(setq git-hash (make-hash-table :test 'equal))

(defun neo-util--hidden-path-filter (node)
  "A filter function, if the NODE can not match each item in \
`neo-hidden-regexp-list', return t."
  (if (not neo-buffer--show-hidden-file-p)
      ;;(let ((shortname (neo-path--file-short-name node)))
        ;;(if (null (neo-util--filter
        ;;       (lambda (x) (not (null (string-match-p x shortname))))
        ;;       neo-hidden-regexp-list))
                 (if (is-in-git-repository node)
                     node
                  )
         ;;           t
         ;;      )
         ;;      )
    node))
```

**Comment by tobimensch** [comment]
By the way, anyone if free to use this code under whatever license they wish.

**Comment by hectormenendez** [comment]
Hey @tobimensch, I just wanted to let you know that I took inspiration on your solution and implemented a simpler one using `git check-ignore`. I debugged it and it isn't that slow (tough it can be improved), thanks for posting! it helped me to resolve this annoying issue. Hope someone suffering like I did find this on google.

```lisp
(defun neo-util--hidden-path-filter (node)
    "it reads each nodule on the list, and determines if its ignored on by git."
    (if (not neo-buffer--show-hidden-file-p)
        ;; hidden-files must be processed
        (if
            ;; git check-ignore returns output only when the file is ignored
            ;; so, if the output is empty (file should be shown) return the node
            (string=
                (string-trim
                    (shell-command-to-string
                        (format
                            "git -C %s check-ignore %s"
                            (file-name-directory node)
                            node
                        )
                    )
                )
                ""
            )
            node
            ;; file should be be hidden
            nil
        )
        ;; show all files
        node
    )
)
```

**Comment by Abdisalan** [comment]
Seems like this is resolved
