### ISSUE TITLE
Cursor goes to the top when un/folding a folder

### ISSUE THREAD

**Issue by tobimensch** [jaypei/emacs-neotree#186]
When un/folding a folder either with RET or with quick-look, the cursor is put at the top.

I think the cursor should stay right where it is (at the folder that you opened/closed).

**Comment by aborn** [comment]
It doesn't remember the last cursor position when \*NeoTree* content refresh.

**Comment by tobimensch** [comment]
@aborn 
But should it not?

**Comment by aborn** [comment]
No, it should be remember!

**Comment by VernonGrant** [comment]
Same problem here. :+1:

**Comment by bmag** [comment]
Experiencing the same problem. Seems to be caused by https://github.com/jaypei/emacs-neotree/commit/ed820107db63cb4f4035616b0d9ef6c9f4ecdc7d. `save-excursion` restores `point` when it exits, so when used inside of `neo-buffer--refresh` it probably cancels the effect of `neo-buffer--goto-cursor-pos`. This modified version of `neo-buffer--refresh` appears to be working, but I haven't tested for any side effects (I didn't even read the rest of the function):
```elisp
(defun neo-buffer--refresh (save-pos-p)
  "Refresh the NeoTree buffer.
If SAVE-POS-P is non-nil, it will be auto save current line number."
  (save-excursion
    (let ((start-node neo-buffer--start-node))
      (unless start-node
        (setq start-node default-directory))

      (neo-buffer--with-editing-buffer
       ;; save context
       (when save-pos-p
         (neo-buffer--save-cursor-pos))
       ;; starting refresh
       (erase-buffer)
       (neo-buffer--node-list-clear)
       (neo-buffer--insert-banner)
       (setq neo-buffer--start-line neo-header-height)
       (neo-buffer--insert-tree start-node 1))))
  ;; restore context
  (neo-buffer--goto-cursor-pos))
```

**Comment by aborn** [comment]
Sorry, it's my fault. Already removed save-excursion. Previously, adding save-excursion only for fixing *NeoTree* position bug when neotree-refresh be called in another buffer.

**Comment by tgroshon** [comment]
Thanks for finding and responding to this issue so quickly!

Does reverting `save-excursion` fix this issue?  And has the fix been published?

**Comment by aborn** [comment]
It's not published yet. The next [melpa](https://melpa.org/#/neotree) building round will publish the latest code.

**Comment by tgroshon** [comment]
I just updated with the latest melpa build and can confirm the bug is fixed!

Thanks for your work!
