### ISSUE TITLE
Customize confirmations

### ISSUE THREAD

**Issue by sumproxy** [jaypei/emacs-neotree#190]
I want to be able to customize (disable) neotree confirmations for create file/dir, delete a dir recursively after confirming the general delete action and kill buffers. I believe this is not a difficult enhancement to implement. 

Thanks.

**Comment by aborn** [comment]
@sumproxy PR is welcome

**Comment by sumproxy** [comment]
@aborn submitted https://github.com/jaypei/emacs-neotree/pull/200, please consider
