### ISSUE TITLE
neotree opens two neotree windnows

### ISSUE THREAD

**Issue by jethrokuan** [jaypei/emacs-neotree#191]
Any call `neotree`-related commands opens up two windows, as shown below:

![](http://i.imgur.com/sJ3J8q4.png)

calling `neotree-toggle` again closes only one of them, and the other is only closable with `C-x 0`.

**Comment by tobimensch** [comment]
I encountered this problem, too.

**Comment by jethrokuan** [comment]
ELISP> neo-global--window
#<window 10 on  *NeoTree*>
ELISP> (neo-global--get-buffer)
#<buffer  *NeoTree*>

It is noted that both windows show "D:10" in the modeline

Regards,
Jethro Kuan

**Comment by aborn** [comment]
Could you provide your os type ?

**Comment by jethrokuan** [comment]
```
❯ lsb_release -rd                                                                             11:31:36 PM 
Description:	Manjaro Linux
Release:	16.08

GNU Emacs 24.5.1
```

**Comment by aborn** [comment]
@jethrokuan Do you use the latest version from melpa?

**Comment by aborn** [comment]
Util now, I use a tiny emacs config in ubuntu linux, it works well.

**Comment by jethrokuan** [comment]
@aborn yes I do. I deleted my entire elpa folder, and reinstalled, with the same issue.

**Comment by aborn** [comment]
PR https://github.com/jaypei/emacs-neotree/pull/197 optimus the function neo-default-display-fn, @jethrokuan pls try again.

**Comment by jethrokuan** [comment]
@aborn that fixed it, thanks a lot!
