### ISSUE TITLE
Excess indentation when using (setq neo-theme 'icons)

### ISSUE THREAD

**Issue by ahawad** [jaypei/emacs-neotree#192]
For some reason the indentation when using the 'icons theme is huge. I am not sure where
the issue is (I am fairly new to emacs).  I have attached an image that displays the issue:

![excess-indent](https://cloud.githubusercontent.com/assets/9411759/18693156/a9da2e1c-7fb0-11e6-8a9a-6d89b9501d69.png)

My neotree config:
```
(setq neo-theme 'icons)
(setq-default neo-smart-open t)
(global-set-key [f8] 'neotree-toggle)
```

**Comment by aborn** [comment]
it seems strange

**Comment by ahawad** [comment]
It does indeed. In case it matters I am running emacs 24.1 on kubuntu 16.04.

**Comment by aborn** [comment]
Can you try it in emacs 24.5 or 25.1 version on kubuntu?

**Comment by ahawad** [comment]
I installed emacs 24.5, backed-up my ~/.emacs.d, and added a minimum init.el that added melpa.
I then proceeded to install `neotree` and `all-the-icons`. Finally, I added the configuration from the listing above. The result is, unfortunatelly, the same.
![excess-indent-emacs-24 5](https://cloud.githubusercontent.com/assets/9411759/18707513/7bde9bea-8007-11e6-90db-32dcc41e5fd5.png)

**Comment by aborn** [comment]
try change the tab-width value
`(setq-default tab-width 2)`

**Comment by ahawad** [comment]
After using `(setq-default tab-width 2)`:
![excess-indent-3](https://cloud.githubusercontent.com/assets/9411759/18710497/a8de174c-8016-11e6-8f82-bd2f98f79a84.png)
It fixes the excessive indentation issue, but it seems like there is still something wrong in the indentation
level of files when compared to directories.

**Comment by aborn** [comment]
I have open a PR https://github.com/domtronn/all-the-icons.el/pull/18 for better fix this problem.

**Comment by ahawad** [comment]
Thank you for your help with this issue :+1:

**Comment by domtronn** [comment]
Sorry to weigh in, but I'd still recommend using tabs for the padding between the icons as this ensures that the file names after the icons line up as all of the icons have variable widths...

Perhaps you could add something for NeoTree to `(setq-local tab-width 1)`? I think this is what I used when integration `all-the-icons` with NeoTree..

**Comment by aborn** [comment]
`(setq-local tab-width 1)` is a better way, I will change it!

**Comment by ahawad** [comment]
I updated it and it works :+1:  Thanks for the work
