### ISSUE TITLE
"Wrong type argument: window-live-p, nil"

### ISSUE THREAD

**Issue by stefanoric** [jaypei/emacs-neotree#193]
Sometimes (and I not quite sure how to consistently reproduce this) when I click on a file on the neo-tree tree, I get the error:

"Wrong type argument: window-live-p, nil"

Some more info captured by `report-emacs-bug`. Glad to provide more info if needed.

> In GNU Emacs 25.1.1 (x86_64-apple-darwin15.5.0, NS appkit-1404.47 Version 10.11.5 (Build 15F34))
>  of 2016-09-20 built on *******
> Windowing system distributor 'Apple', version 10.3.1404
> Configured using:
>  'configure --disable-dependency-tracking --disable-silent-rules
>  --enable-locallisppath=/usr/local/share/emacs/site-lisp
>  --infodir=/usr/local/Cellar/emacs/25.1/share/info/emacs
>  --prefix=/usr/local/Cellar/emacs/25.1 --without-x --with-xml2
>  --without-dbus --without-gnutls --with-rsvg --with-ns
>  --disable-ns-self-contained'
> 
> Configured features:
> JPEG RSVG NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
> 
> Important settings:
>   value of $LANG: en_GB.UTF-8
>   locale-coding-system: utf-8-unix
> 
> Major mode: NeoTree
> 
> Minor modes in effect:
>   global-flycheck-mode: t
>   global-auto-complete-mode: t
>   yas-global-mode: t
>   yas-minor-mode: t
>   show-paren-mode: t
>   editorconfig-mode: t
>   projectile-global-mode: t
>   projectile-mode: t
>   diff-auto-refine-mode: t
>   magit-auto-revert-mode: t
>   global-git-commit-mode: t
>   async-bytecomp-package-mode: t
>   shell-dirtrack-mode: t
>   global-undo-tree-mode: t
>   undo-tree-mode: t
>   evil-mode: t
>   evil-local-mode: t
>   tooltip-mode: t
>   global-eldoc-mode: t
>   mouse-wheel-mode: t
>   menu-bar-mode: t
>   file-name-shadow-mode: t
>   global-font-lock-mode: t
>   blink-cursor-mode: t
>   auto-composition-mode: t
>   auto-encryption-mode: t
>   auto-compression-mode: t
>   buffer-read-only: t
>   column-number-mode: t
>   line-number-mode: t
>   transient-mark-mode: t

**Comment by aborn** [comment]
Didn't find the any call `window-live-p` function in neotree source code. It's seems strange.

**Comment by stefanoric** [comment]
I think I have found a way to reproduce it. It might have something to do with [Magit](https://github.com/magit/magit):

1. Start up Emacs
2. Open neo-tree (neotree-toggle)
3. Click on a file in neo-tree
4. Verify that neo-tree opens the file
5. Start Magit (magit-status)
6. Click again on a file in neo-tree
7. Error: "Wrong type argument: window-live-p, nil". File does not open.

**Comment by aborn** [comment]
`M-x toggle-debug-on-error` and print *Backtrace*.

**Comment by stefanoric** [comment]
Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  #<subr select-window>(nil nil)
  ad-Advice-select-window(#<subr select-window> nil)
  apply(ad-Advice-select-window #<subr select-window> nil)
  select-window(nil)
  neo-global--select-mru-window(nil)
  neo-open-file("/Users/<****>.js" nil)
  neo-buffer--execute(nil neo-open-file #[(&rest _) "\300\207" [nil] 1])
  #[(&optional arg) "\301 \210\302\303\304#\207" [arg neo-global--select-window neo-buffer--execute neo-open-file #[(&rest _) "\300\207" [nil] 1]] 4 nil "P"](nil)
  funcall-interactively(#[(&optional arg) "\301 \210\302\303\304#\207" [arg neo-global--select-window neo-buffer--execute neo-open-file #[(&rest _) "\300\207" [nil] 1]] 4 nil "P"] nil)
  call-interactively(#[(&optional arg) "\301 \210\302\303\304#\207" [arg neo-global--select-window neo-buffer--execute neo-open-file #[(&rest _) "\300\207" [nil] 1]] 4 nil "P"] nil nil)
  command-execute(#[(&optional arg) "\301 \210\302\303\304#\207" [arg neo-global--select-window neo-buffer--execute neo-open-file #[(&rest _) "\300\207" [nil] 1]] 4 nil "P"])

**Comment by aborn** [comment]
@stefanoric Please try the latest netree from melpa.

**Comment by stefanoric** [comment]
Tried, but same error as before unfortunately (I have installed 20161013.808).

Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  #<subr select-window>(nil nil)
  ad-Advice-select-window(#<subr select-window> nil)
  apply(ad-Advice-select-window #<subr select-window> nil)
  select-window(nil)
  neo-global--select-mru-window(nil)
  neo-open-file("<***>.js" nil)
  neo-buffer--execute(nil neo-open-file #[(&rest _) "\300\207" [nil] 1])
  #[(&optional arg) "\301 \210\302\303\304#\207" [arg neo-global--select-window neo-buffer--execute neo-open-file #[(&rest _) "\300\207" [nil] 1]] 4 nil "P"](nil)
  funcall-interactively(#[(&optional arg) "\301 \210\302\303\304#\207" [arg neo-global--select-window neo-buffer--execute neo-open-file #[(&rest _) "\300\207" [nil] 1]] 4 nil "P"] nil)
  call-interactively(#[(&optional arg) "\301 \210\302\303\304#\207" [arg neo-global--select-window neo-buffer--execute neo-open-file #[(&rest _) "\300\207" [nil] 1]] 4 nil "P"] nil nil)
  command-execute(#[(&optional arg) "\301 \210\302\303\304#\207" [arg neo-global--select-window neo-buffer--execute neo-open-file #[(&rest _) "\300\207" [nil] 1]] 4 nil "P"])

**Comment by palikar** [comment]
Hey @stefanoricm, are you still having the problem?

**Comment by stefanoric** [comment]
@palikar I have moved to spaceemacs from a vanilla install, and haven't got any issues since.

**Comment by palikar** [comment]
Great, thanks for the feedback.
