### ISSUE TITLE
Problem with getting all-the-icons-applied

### ISSUE THREAD

**Issue by tatsuhirosatou** [jaypei/emacs-neotree#194]
If I run `(setq neo-theme (if window-system 'icons 'arrow))` using `eval-region` I can see the all-the-icons theme being applied. But if I run it from my init file it never gets applied.

**Comment by tatsuhirosatou** [comment]
The problem was that since I am using emacsclient, it defaults to arrow when `emacs --daemon` is run. Any alternative to `(setq neo-theme (if window-system 'icons 'arrow))` for `emacs --daemon` users?

**Comment by aborn** [comment]
The variable window-system's value is nil when run emacs as daemon mode.

**Comment by ykyuen** [comment]
I got the same problem which [all-the-icons](https://github.com/domtronn/all-the-icons.el/wiki#neotree-now-supported-natively) doesn't show up in the neotree when running emacs in client/server mode.

The workaround is setting the neo-theme in `after-make-frame-functions` hook instead of the use-package config.

```lisp
;; all-the-icons
;; https://github.com/domtronn/all-the-icons.el
(use-package all-the-icons
  :ensure t)

;; A workaround for missing all-the-icons in neotree when starting emacs in client mode
;; Ref:
;;   - https://github.com/jaypei/emacs-neotree/issues/194
;;   - https://emacs.stackexchange.com/questions/24609/determine-graphical-display-on-startup-for-emacs-server-client
(defun new-frame-setup (frame)
  (if (display-graphic-p frame)
      (setq neo-theme 'icons)))
;; Run for already-existing frames (For single instance emacs)
(mapc 'new-frame-setup (frame-list))
;; Run when a new frame is created (For emacs in client/server mode)
(add-hook 'after-make-frame-functions 'new-frame-setup)
```

Hope this help. =)
