### ISSUE TITLE
Make a new release on MELPA stable

### ISSUE THREAD

**Issue by ZzAntares** [jaypei/emacs-neotree#196]
Hi, on MELPA stable last release is `v0.2.1` that was 2 years ago, since then a lot of features have been added to the project, such features are not available when downloading via MELPA stable which is a recommended distribution channel to use in most of the Emacs packages.

Thanks.

**Comment by aborn** [comment]
The new version 0.5 released!

**Comment by ZzAntares** [comment]
👍
