### ISSUE TITLE
Lock-ups when invoking certain actions whilst NeoTree is the active buffer

### ISSUE THREAD

**Issue by cmacrae** [jaypei/emacs-neotree#206]
Whenever I perform certain actions with NeoTree being the active buffer, it makes Emacs lock up and I have to force quit the process. I'm running Emacs 25 on macOS.

By certain actions, from what I've observed, it seems to be two prominent actions:  
- Any Magit interaction
- Any Projectile interaction

This behaviour is present in both Emacs 24 & 25.

If there is any further information I can provide, please let me know. But; bear in mind, I'm not able to interact with Emacs at all once this lock-up occurs, so I won't be able to access any other buffers, etc.

**Comment by aborn** [comment]
Try to remove magit pkg, emacs performs normal?

**Comment by aborn** [comment]
Try to remove magit pkg, emacs performs normal?

**Comment by aborn** [comment]
Try to remove magit pkg, emacs performs normal?

**Comment by cmacrae** [comment]
Well, strangely enough: even though I'd already tried a "fresh set-up" several times, I just removed all my local resources for my Emacs config today, re-installed all packages, etc, and this behaviour has now disappeared! 🎉 

I'll close this off - but if it arrises again, I'll re-open this with more details, and try without `magit` as @aborn suggested :)
