### ISSUE TITLE
哥们儿，太赞了， 这是我用过最好的项目文件浏览器，没有之一。

### ISSUE THREAD

**Issue by zw963** [jaypei/emacs-neotree#207]
太激动了，竟然是国人做的！！！

**Comment by zw963** [comment]
如果打扰了， 抱歉抱歉。

**Comment by zw963** [comment]
给些建议：

1. README 可以更详细一些, 例如某些常用的定制选项， 不是谁都愿意看 elisp 源码的。
2. 默认 F8 是不错， 但是其实鼠标右键作为切换也是不错的？

**Comment by zw963** [comment]
3. 左侧的导航栏没有根据当前打开的文件自动变化刷新。这点，https://github.com/sabof/project-explorer 做的蛮好的。

**Comment by zw963** [comment]
4. 手动调整了宽度， 打开一个新的文件，又恢复成默认宽度了。

**Comment by aborn** [comment]
(setq neo-window-fixed-size nil)

**Comment by zw963** [comment]
@aborn , 多谢.


> 试下 (setq neo-window-fixed-size nil)

无效啊, 该是自动弹回, 我用的是 emacs daemon  GUI 模式, 不知是否与这个有关.


另外有一个让我很纠结的问题, 请教下.

我常常希望重命名项目中的 `目录/文件` 名称, 之前我都是用 dired 模式的,
neo 的确好用, `r`, `c` 之类的快捷键很赞,  但是有个问题, 当我用鼠标
 点击文件时, 此时我的本意是想重命名这个文件, 可是往往操作是 打开了
这个文件, Point 跳到了文件当中,  类似情形, 你是如何解决的?

**Comment by aborn** [comment]
1. 那你试下不用daemon模式下，用正常的GUI下看调整宽度是否有效。
2. 在我用emacs的时候，我是disable mouse的。所以，我会用`r, c `之类快捷键。

**Comment by zw963** [comment]
谢谢. 

>> 那你试下不用daemon模式下，用正常的GUI下看调整宽度是否有效。

我尝试了, 不用 daemon 和用  daemon 一样的, 不过, 我发现, 在设定 
`(setq neo-window-fixed-size nil)` 情况下,  偶尔是可以调整的.

总之需要按下鼠标不放, 左右多挪一挪, 才有可能生效. 
一旦生效了, 就可以工作了. : )

非常感谢.
