### ISSUE TITLE
switch-to-buffer-other-window opens frame when  'split-width-threshold is nil

### ISSUE THREAD

**Issue by bretweinraub** [jaypei/emacs-neotree#209]
Emacs 25.1

I removed nearly everything from my .emacs, to make sure it wasn't me.

I have this:

(require 'neotree)
(setq neo-smart-open t)
(define-key neotree-mode-map (kbd "i") #'neotree-enter-horizontal-split)
(define-key neotree-mode-map (kbd "I") #'neotree-enter-vertical-split)

;; i like horizontal splits because, that's the way Emacs was originally!!!!
(setq split-width-threshold nil)

so open neotree, make sure you have one other window open, and do C-x-4-b otherwise know as switch-to-buffer-other-window.

And it opens a new frame ....

**Comment by bretweinraub** [comment]
For the moment, I've had to abandon neotree....

**Comment by aborn** [comment]
Sorry for delay reply. This is a bug!

**Comment by aborn** [comment]
This bug already fixed in https://github.com/jaypei/emacs-neotree/commit/cfef6036b69d53a83689694f5f257e5aaaeef265 . Add flowing setting in your init file:
`(setq split-window-preferred-function 'neotree-split-window-sensibly)`

**Comment by bretweinraub** [comment]
Works for me!   Thanks!
