### ISSUE TITLE
How to change neotree's font size?

### ISSUE THREAD

**Issue by peteyy** [jaypei/emacs-neotree#218]

**Comment by ZelphirKaltstahl** [comment]
I'd like to know that too.

**Comment by lukertty** [comment]
```elisp
(defun text-scale-twice ()(interactive)(progn(text-scale-adjust 0)(text-scale-decrease 2)))
(add-hook 'neo-after-create-hook (lambda (_)(call-interactively 'text-scale-twice)))
```

Try this.

**Comment by ZelphirKaltstahl** [comment]
I think I found the settings somewhere in the emacs config. There was no need to code something. I found the following was automatically added to my config file:

    (custom-set-faces
     '(cursor ((t (:background "gold" :foreground "#151718"))))
     '(mode-line ((t (:background "black" :foreground "#4499FF"))))
     '(neo-dir-link-face ((t (:foreground "deep sky blue" :slant normal :weight bold :height 120 :family "Fantasque Sans Mono"))))
     '(neo-file-link-face ((t (:foreground "White" :weight normal :height 120 :family "Fantasque Sans Mono"))))
    ...
 '(neo-root-dir-face ((t (:foreground "lightblue" :weight bold))))
