### ISSUE TITLE
master branch is out of date compared to dev branch, for el-get

### ISSUE THREAD

**Issue by mstorus** [jaypei/emacs-neotree#219]
Hi,
I noticed that the `dev` branch has many more new features compared to the `master` branch.

This caused confusion for me because I use `el-get` to install neotree, and the `el-get` version uses the `master` branch 
https://github.com/dimitri/el-get/commit/0b560eec7b04054602916ced835d338dd0c9d438

Last commit on `master` is from `Mon Sep 8 21:15:00 2014 +0800`
Last commit on `dev` is from `Tue Jan 10 19:21:31 2017 +0800`

therefore I was missing a lot of new features.

There are two ways I can think to fix this:
1) use the `dev` branch for `el-get`
2) release the new `dev` code onto `master`

What do you think?

**Comment by aborn** [comment]
The master branch keep stable, and the dev branch for develop and keep latest features. I released the dev code onto master just now.
