### ISSUE TITLE
getting 'Cannot make side window the only window' when trying to create/rename node

### ISSUE THREAD

**Issue by nadeemkhedr** [jaypei/emacs-neotree#226]
Whenever I try to create/rename I get this error 
```
Cannot make side window the only window' when trying to create/rename node
```

this happened recently after I upgraded all the emacs packages, was working before
tried to investigate a little and found the exception is thrown [here](https://bitbucket.org/hgiddens/emacs/src/9183cc0697064355d1704f1d4b5eba006656706a/lisp/window.el?at=srgb-colours&fileviewer=file-view-default#window.el-3404), hope it helps

**Comment by oyvindeh** [comment]
I get the same error when trying to display NeoTree help or use Helm when the NeoTree window is in focus. I also suddenly seem to have gotten this after upgrading packages.

**Comment by cescoferraro** [comment]
It was all working yesterday. Then now I cant get ride of the error.

**Comment by dennismayr** [comment]
It's still happening as of Oct 21 2017.

Any ideas?

**Comment by abs-zero** [comment]
I am having this problem, too.

**Comment by katafrakt** [comment]
Same here. I tried a couple of things like nuking elpa and reinstalling everything, but nothing helps.

**Comment by bapcyk** [comment]
the same: in Spacemacs, when I try to create, copy...

**Comment by dennismayr** [comment]
Try exiting and saving desktop, reopening Emacs, `M-x desktop-read`, and toggling `neotree`; then try renaming a file or directory with `C-c C-r`.
I updated Spacemacs last night and upgraded packages this morning, and the problem is still there.

**Comment by abs-zero** [comment]
spacemacs' develop branch fixed it for me

**Comment by nukeop** [comment]
I'm seeing this issue too. Installed from melpa, not using spacemacs.

**Comment by ignatirabo** [comment]
I'm also having this issue with Evil mode. Can't create, rename, change root, etc. I can only open files.

**Comment by doubleagent** [comment]
I am also seeing this issue.

**Comment by Trioblack** [comment]
Me too.

**Comment by gabriel128** [comment]
me too

**Comment by RX14** [comment]
Please 👍 the issue instead of adding "me too" comments. It's obvious this is happening, such comments don't add any new information.

**Comment by voldy** [comment]
Installing spacemacs from develop branch fixed this issue for me.

**Comment by nukeop** [comment]
Can you point to the patch that fixed it? Most people probably don't want to install everything in spacemacs to get rid of the issue.

**Comment by jacderida** [comment]
Is there a workaround if you're not using Spacemacs? I'm seeing the issue in Emacs 25.3 with Evil mode.

**Comment by karmajunkie** [comment]
I'm also getting this error when I try to create a new file. Interestingly, when I have neotree open, then switch to a new workspace (using `eyebrowse-switch-to-window-config-X` (where `X` is the number of the new workspace) neotree goes back to working normally. I assume this is because when eyebrowse copies the current workspace into the new one, neotree's window is not copied as a side window but a regular one. But if i then close the neotree window and reopen it (using `SPT p t` in my case, also behaves the same with `M-x neotree-show`) I get the side window error again.

Spacemacs on the develop branch fixes the issue bug creates many new problems for me. Would very much appreciate any pointers on fixing this or reverting to a different version.

**Comment by apmiller108** [comment]
This happens to me occasionally. What works for me is syncing my dotspacemacs file (`SPC f e R`).  After that, for a while I no longer get `Cannot make side window the only window` when attempting to create or rename nodes.

**Comment by howdoicomputer** [comment]
Awh man, this is hitting me as well and, like @apmiller108, it was after syncing my dotfile. I just... have been coming across show-stopping bugs in Spacemacs the last few days and I just cannot get any work done. Anyway, are there any changes made between master and develop that touch neotree or helm? I might go spelunking with git log to find out.

**Comment by mirubiri** [comment]
Try `SPC-fed` and then `SPC-feR`, I have noticed that the problem is fixed when reloading `.spacemacs` something weird here.

**Comment by Nek** [comment]
@mirubiri Thanks! It helped me too. This is such a weird bug.

**Comment by karmajunkie** [comment]
Fixes the state of things for me. I think this is consistent with what I reported above—taking some action that has emacs itself rearranging or duplicating layouts recreates the neotree window as a "full window" (I'm not sure what the correct terminology is) whereas opening it via neotree's functions creates it as a side window, producing the problem doing anything that's going to create a helm buffer or whatever is happening under the covers. (I'm probably butchering the terminology, forgive me—relative newbie to the emacs ecosystem.)

**Comment by gen1321** [comment]
I still have same issue. `SPC-feR` do not working for me

**Comment by Alex-Lin** [comment]
SPC-feR work for me

**Comment by kkweon** [comment]
<kbd>SPC</kbd> <kbd>f</kbd><kbd>e</kbd><kbd>R</kbd> indeed fixed it. 
It's weird :thinking:

**Comment by dineshbhosale** [comment]
This issue still exists, pressing "SPC feR" again and again does not feel productive at all.

**Comment by dineshbhosale** [comment]
Same error occurs when neotree is open and you try to open a new EShell buffer. I believe it is a problem with neotree itself. Pressing SPC feR again and again feels painful.

**Comment by s9gf4ult** [comment]
I have two machines:

1. 
Neotree:  `20170522.758 (melpa).` 

Emacs: 

```
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19)
 of 2017-09-27
Copyright (C) 2017 Free Software Foundation, Inc.
```

2. 

neotree:  `20170522.758 (melpa).` 

Emacs:

```
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.20.6)
 of 2016-07-31
Copyright (C) 2015 Free Software Foundation, Inc.
```

The problem reproduces on machine 1, but not repreduces on machine 2. So it looks like the problem of `neotree` with `Emacs 25`.

**Comment by s9gf4ult** [comment]
And yes. Pressing `SPC-feR` does not help for me.

**Comment by denniscual** [comment]
Pressing `SPC-feR` helps me. But when I tried to restart the spacemac, the error is threw again.

**Comment by denniscual** [comment]
Pressing `SPC-feR` helps me. But when I tried to restart the spacemac, the error is threw again. 
 
In my machine 1 emacs version: 
  `I've been using emacs version 25.1.1 `
   **No error**

Machine 2 emacs version:  
  `Emacs version 24.5.1`
  **Cannot make side window the only window**

So I think the problem is not on the version of emacs but when updating the spacemac packages.

**Comment by 9mm** [comment]
`SPC f e R` works for me, but is lame...

**Comment by briansunter** [comment]
I'm having this problem too

**Comment by dineshbhosale** [comment]
Tried upgrading to develop branch ?

**Comment by keown** [comment]
same issue here using spacemacs

**Comment by zhipengyan** [comment]
```SPC f e R```  works for me If I jump to another buffer which is not .spacemacs

**Comment by Crandel** [comment]
Does anybody have solution for emacs, not spacemacs? Very annoing bug.

**Comment by unalterable** [comment]
I'm on spacemacs (master branch) and i think this has worked for me (and i think it should work with emacs too):
```
(setq helm-split-window-inside-p t)
```
I put it in my user -config() (which is a set of commands run after spacemacs loads all its layers/packages)

**Comment by Crandel** [comment]
I played with my config and found source of issue. I disable (helm-autoresize-mode 1) and everything start working again

**Comment by s9gf4ult** [comment]
@Crandel confirm the same, works for me. thanks.

**Comment by sr105** [comment]
None of the methods described work for me:

- `(setq helm-split-window-inside-p t)` in user-config
- `(helm-autoresize-mode 1)` in user-config
- SPC feR

I'm using 0.200.13@24.5.1 (spacemacs).

**Comment by Crandel** [comment]
@sr105 
I commited `(helm-autoresize-mode 1)` and everything start working

**Comment by wzin** [comment]
`'(helm-autoresize-mode 1)` works for me as well in spacemacs ` 0.200.13@25.3.2 (spacemacs)`

**Comment by Trioblack** [comment]
After update the spacemacs to `0.200.13@25.3.1` the same issue appears.

So far `(helm-autoresize-mode 1)` make it work again.

**Comment by arunas-smala** [comment]
Had the same issue, but updating packages helped:
1) `configuration-layer/update-packages`
2) `spacemacs/restart-emacs`

**Comment by hsg777** [comment]
(setq helm-split-window-inside-p t) in user-config of spacemacs on mac worked for me. Thanks

**Comment by Kagemaru** [comment]
Thanks @unalterable, works now. :)

**Comment by jaypei** [comment]
Thanks @nadeemkhedr  @unalterable .

NeoTree uses `display-buffer-in-side-window` to show sidebar mode,
this conflicts with the latest version of Helm.

**Comment by jottos** [comment]
? (help) in neotree still  does not work
(neotree-20181121.2026  and  helm-20200128.1831)

if you bring up helm, then move focus to neotree and then do '?' help will come up
otherwise you get the error. Non of the helm variable fixes or reloads work

do folks just live with this?

**Comment by nukeop** [comment]
>do folks just live with this?

Unfortunately yes
