### ISSUE TITLE
如果开启两个 Frame, 无法同时开启两个独立的 Neotree

### ISSUE THREAD

**Issue by zw963** [jaypei/emacs-neotree#227]
如题.

例如: 我在 Linux 下的不同桌面, 会开启两个 Emacs frame, 这里的 Fframe 指的是
我启动了一个 emacs daemon, 但是通过 emacsclient 启动了两个终端.
此时, 在不同的界面, 均按下 F8 开启 neotree, 但是此时, 操作其中一个, 另一个也会
跟着动, 其实这个时候, 是希望像其他编辑器那样, 一个开启 Project1, 另一个开启 Project2,
这在当前版本下是不可能的.

**Comment by palikar** [comment]
I have no idea what is the issue about but this was allegedly fixed in #280 . Feel free to reopen if the issue is about something else. Also, English (or German or Bulgarian) would be appreciated. Sorry, I don't understand Chinese :( .
