### ISSUE TITLE
Rename/Move files and directories

### ISSUE THREAD

**Issue by f0086** [jaypei/emacs-neotree#23]
NerdTree has a handy feature to rename/move folders and files. I used this feature extremely often, so I think this is a missing key feature. neotree already can create and delete files and folders, so renaming/moving (technically the same feature) should be implemented.

**Comment by khaquachtrong74** [comment]
Yes, you right. but now is 2025, and I still don't find syntax or information about renaming feature folders (but it have copy and move folder or file)
