### ISSUE TITLE
Problem with vc.el

### ISSUE THREAD

**Issue by Crandel** [jaypei/emacs-neotree#232]
[Here](https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el#L78) you use file **vc.el** for loading vc-responsible-backend function

`(autoload 'vc-responsible-backend "vc.el")`

But in my ubuntu 16.04 I use emacs with only \*.elc files from ppa and I have only **vc.elc** file, so I have default face for all files in git directory.
Could you add test and load this function from **vc.elc** if **vc.el** file doesn`t exist?

**Comment by aborn** [comment]
Already changed to autoload vc.elc as default https://github.com/jaypei/emacs-neotree/commit/385f95d25cebdd3fb4476493281c92a13b897b53.
