### ISSUE TITLE
Make cursor invisible

### ISSUE THREAD

**Issue by LukeDefeo** [jaypei/emacs-neotree#233]
Ive managed to customise the fonts and colours to how i like but the last thing is i would like to be able to remove the cursor color, its yellow in the pic

<img width="223" alt="screenshot 2017-03-24 00 21 45" src="https://cloud.githubusercontent.com/assets/2492575/24275485/9a5b12f0-1027-11e7-8dec-7937ce405035.png">

Id just like to use the line accent/highlight. Having a cursor in neotree doesn't seem to make a great deal of sense and just looks a bit ugly.

Any way i can achieve this?

Thanks

**Comment by idoo** [comment]
Partially you can hide cursor for not active buffer with
`(setq-default cursor-in-non-selected-windows nil)`

**Comment by palikar** [comment]
Fixed with #276 .

**Comment by pera** [comment]
Unfortunately `(setq neo-hide-cursor t)` doesn't work with evil-mode. This is related to https://github.com/emacs-evil/evil/issues/592
