### ISSUE TITLE
Conflict with mo-git-blame

### ISSUE THREAD

**Issue by zw963** [jaypei/emacs-neotree#234]
https://github.com/mbunkus/mo-git-blame/issues/19#issuecomment-290690801

**Comment by aborn** [comment]
I have't got your point!

**Comment by zw963** [comment]
sorry for confuse~~

I not enable `emacs-neotree`, mo-git-blame can togle in left panel, 
if enabled, emacs-neotree open the same place as mo-git-blame,
cause mo-git-blame nothing happen.

Fine, I think this maybe a `mo-git-blame` issue, not `neotree`.

**Comment by zw963** [comment]
sorry for confuse ... 

with some settings, it worked.
