### ISSUE TITLE
Follow mode

### ISSUE THREAD

**Issue by idoo** [jaypei/emacs-neotree#238]
Is it possible to enable `follow mode` now? 
For example, I've opened buffer `A` and opened neotree, then switched to buffer `B` but neotree still showing directory where `A` is placed, not `B`
looks like I have to call `neotree-find` when change buffer, right? probably we need that inside neotree package
Thanks :)

**Comment by aborn** [comment]
@idoo upgrade neotree to latest, PR #240 is what's your want!
