### ISSUE TITLE
Open file in current buffer

### ISSUE THREAD

**Issue by threaz** [jaypei/emacs-neotree#239]
Is there a way to make neotree open selected file in the current buffer? The current behaviour is to always use the leftmost one. Shouldn't it work this way by default or am I missing something?

**Comment by aborn** [comment]
When your cursor focused in *neotree* buffer node, use <RET> open & and switch to this file,  use <SPEC> preview current file. The current behavior is what you want ?

**Comment by palikar** [comment]
@threaz  what do you mean with "the current window". When you are in the neotree buffer, the neotree window is the current buffer. Can you clarify what exactly is that you want to achieve?

**Comment by Abdisalan** [comment]
Closing since no new info was given. Please open a new issue if you'd like this feature
