### ISSUE TITLE
Enabling relative line numbers

### ISSUE THREAD

**Issue by jamesla** [jaypei/emacs-neotree#243]
How can I enable relative line numbers in Neotree?

**Comment by aborn** [comment]
Did you mean show line numbers only in *Neotree* buffer ?

**Comment by jamesla** [comment]
Yep, it's something I use in vim. Showing relative line numbers in the neotree buffer means that I can press 9 k to go up 9 lines, allowing me to navigate neotree faster.

**Comment by jamesla** [comment]
Anybody know if this is supported or not?

**Comment by aborn** [comment]
@jamesla Not yet!

**Comment by palikar** [comment]
Hi @jamesla , this really should not be feature of neotree but rather of emacs itself. There is that one package - (nlinum-relative)[https://github.com/CodeFalling/nlinum-relative] - that lets you do exactly this. I just tried it out and it works ok in the neotree buffer.
