### ISSUE TITLE
Only showing files in projects

### ISSUE THREAD

**Issue by benneti** [jaypei/emacs-neotree#246]
When opening neotree it only shows the current directory without the files and folders inside with this error:
`Error running timer ‘neo-global--do-autorefresh’: (error "You’re not in a project")`
Installed Version 20170507.200 (according to list-packages) in emacs 25.2.1 with spacemacs 0.200.9

**Comment by Renkoru** [comment]
The same issue for my custom setup.

@benneti To temporary fix this I have replaced neotree.el file in package folder with this one
https://github.com/jaypei/emacs-neotree/blob/0.5.1/neotree.el from 0.5.1 release.

**Comment by benneti** [comment]
Thank you very much 😊

**Comment by davidelbaze** [comment]
Ok. I'll will see what can be done to resolve this issue. 
You can desactive auto-refresh by setting `(setq neo-autorefresh nil)` in your config file.

**Comment by davidelbaze** [comment]
I've just done a test. It works well event outside a project...

**Comment by aborn** [comment]
The reason is the function `neo-get-unsaved-buffers-from-projectile` when open non-project file.

**Comment by aborn** [comment]
After fix the problem https://github.com/jaypei/emacs-neotree/commit/42b00dd900d49c538f947f47f240a08810580020 , I found another problem when open non-project file. It maybe cause emacs got stuck when switch to another buffer using helm. So, I decide remove https://github.com/jaypei/emacs-neotree/pull/241 temporarily until the problem real solved! https://github.com/jaypei/emacs-neotree/commit/5e1271655170f4cdc6849258e383c548a4e6e3d0
