### ISSUE TITLE
Error: neo-global--do-autorefresh

### ISSUE THREAD

**Issue by nathansizemore** [jaypei/emacs-neotree#248]
With the latest package, opening Emacs, setting neotree to my normal development directory, and just waiting, it will error out after a few seconds with the following error, and removing the entire tree:

```
Error running timer 'neo-global--do-autorefresh': (wrong-type-argument stringp nil)
```

https://github.com/jaypei/emacs-neotree/issues/247 tie in.

**Comment by rhussmann** [comment]
I'm seeing this behavior as well, when opening my home directory in emacs. For what it's worth, I also have `projectile` installed as well.

**Comment by palikar** [comment]
I can't see this problem in the current version of neotree (the latest on the dev branch). Can someone confirm so that I can close the issue?

**Comment by Abdisalan** [comment]
Closing as stale. If you're still experiencing this, please open a new issue.
