### ISSUE TITLE
Path "~/" doesn't resolves well during autorefresh

### ISSUE THREAD

**Issue by pmilosev** [jaypei/emacs-neotree#249]
When I run _Emacs_ with _neotree_ with _neoautorefresh_ set to _t_,
I get an error if the _default-directory_ is _'~/'_:
`Error running timer ‘neo-global--do-autorefresh’: (wrong-type-argument stringp nil)`

By documentation _file-name-absolute-p_ considers _'~/'_ as absolute path, so _neo-path--expand-name_ doesn't do any expansion. Later this get's stripped to _'~'_  in _neo-path--updir_ resulting in a _nil_ being returned by _file-name-directory_.

**Comment by nathansizemore** [comment]
[Original Issue tie in](https://github.com/jaypei/emacs-neotree/issues/248)
