### ISSUE TITLE
Windows 10 icons slow navigation

### ISSUE THREAD

**Issue by sho-87** [jaypei/emacs-neotree#252]
I've set neotree to display icons using the following on Windows 10 emacs 25:

```
(use-package neotree :ensure t
  :config
  (setq neo-theme (if (display-graphic-p) 'icons 'arrow))
  )
```

I'm running into the same problem as described here: https://github.com/domtronn/all-the-icons.el/issues/28

Whenever I toggle neotree, the icons display correctly, but navigation is extremely slow. Everything is fine again after I hide neotree. This happens in both git projects and also non-git directories

Any thoughts on what might be causing this?

**Comment by aborn** [comment]
which version do you used ?

**Comment by sho-87** [comment]
I  believe its the latest. `list-packages` says `20170522.758`

**Comment by paraschivescu** [comment]
I'm having the same issue, Emacs 25.1.1 and Windows 10. 

Thinking it may have something to do with ClearType on Windows, I disabled it, to no avail.

I also tried the solution proposed in the referenced thread:

`(setq inhibit-compacting-font-caches t)`

But it didn't work. :(

**Comment by VJatla** [comment]
For me this worked from [domtronn/all-the-icons.el#28](https://github.com/domtronn/all-the-icons.el/issues/28)

`(setq inhibit-compacting-font-caches t)`

**Comment by Abdisalan** [comment]
Closing as stale. If you're still experiencing this, please open a new issue.
