### ISSUE TITLE
It always switches to the current file dir.

### ISSUE THREAD

**Issue by zilti** [jaypei/emacs-neotree#257]
Even when in a projectile project, neotree always switches to the directory of the file I'm editing. I can do `M-x neotree-projectile-action` all I want, it switches back after a few seconds.

**Comment by zilti** [comment]
Ok, I see this is a known problem. Sorry! :)

**Comment by ZzAntares** [comment]
Hello @zilti how did you fixed it? I don't know if this is a bug or a feature, I don't want it.

**Comment by palikar** [comment]
@ZzAntares , you can try turning off the `smart open` feature. You can find it in the customizations Group `Neotree`

**Comment by ZzAntares** [comment]
Hey @palikar thanks for the hint, it seems the `neo-smart-open` does exactly what I don't want it to do, event after setting it to `nil` it keeps doing the same thing, couldn't be this a bug that always ignore this setting and does the smart open thing always @jaypei?

**Comment by palikar** [comment]
@ZzAntares, I don't think so. Can you make sure that you are using the function `neotree-toggle` to open neotree and not `noetree-find`.

**Comment by ZzAntares** [comment]
@palikar, yes I'm using `neotree-toggle`, could you pleas take a look on my settings to see if it's something wrong with it?

```elisp
(use-package neotree
  :hook (neotree-mode . (lambda ()
                          (setq buffer-face-mode-face '(:family "Hack" :height 130 :width semi-condensed))
                          (buffer-face-mode)))

  :commands neotree-make-executor

  :config
  (setq neo-smart-open nil
        neo-window-width 30
        neo-theme (if (display-graphic-p) 'icons 'arrow)
        projectile-switch-project-action 'neotree-projectile-action)

  :general
  (:states 'normal "M-1" 'neotree-toggle)
  (:keymaps 'normal
   :prefix "SPC"
   "tl" 'neotree-toggle)
  (:states 'normal
   :keymaps 'neotree-mode-map
   "o" (neotree-make-executor
        :file-fn 'neo-open-file
        :dir-fn  'neo-open-dir)
   "md" 'neotree-delete-node
   "ma" 'neotree-create-node
   "mm" 'neotree-rename-node
   "C" 'neotree-change-root
   "R" 'neotree-refresh
   "TAB" 'neotree-enter
   "?" 'describe-mode
   "A" 'neotree-stretch-toggle
   "H" 'neotree-hidden-file-toggle
   "n" 'next-line
   "p" 'previous-line
   "q" 'neotree-hide
   "u" 'neotree-select-up-node))
```
