### ISSUE TITLE
Emacs makes a new window instead of splitting it when neotree is open.

### ISSUE THREAD

**Issue by bluesd** [jaypei/emacs-neotree#258]
Whenever neotree's window is showing, functions which should split the current pane (like describe-key, ag searches, etc) open a totally new separate window instead.

**Steps to reproduce**
1. Open emacs
2. Open neotree
3. Move to main window
4. Exec, for example, `M-x isearch-describe-key`
5. Help dialog is now open in a new window instead of the current one.
If you do the same without neotree, then the split occurs as expected.

Does anyone know if this behavior is neotree related, or there's something in emacs about the widths of buffers to determine where the new window will be opened?

**Comment by Abdisalan** [comment]
Closing as stale. If you're still experiencing this, please open a new issue.
