### ISSUE TITLE
Bug with helm : Attempt to delete minibuffer or sole ordinary windows

### ISSUE THREAD

**Issue by llacom** [jaypei/emacs-neotree#26]
This is a weird bug and may happen because of something else on my config (don't see why it would, but then again I don't see how neotree does this).

After opening say helm-mini, trying to open helm help (with "C-c ?") gives the following error : Attempt to delete minibuffer or sole ordinary windows 

I have these two lines on my config (and when I comment them the bug goes away) : 
     (add-to-list 'load-path (concat user-emacs-directory "/vendor/neotree"))
     (require 'neotree)

**Comment by ReneFroger** [comment]
I have the same bug.
