### ISSUE TITLE
Crash on start of neotree buffer

### ISSUE THREAD

**Issue by ACHinrichs** [jaypei/emacs-neotree#261]
Hi,

every time I start NeoTree, emacs crashes with 
```
Fatal error 11: Segmentation fault
...
```
This error occurs on Ubuntu 17.04 with GNU Emacs 25.1.1.
Under windows 10 with the same emacs version it is just slow as hell (response time for arrow keys > 1 sec).
I installed both NeoTree and all-the-icons from mepla
My configuration can be found [here](https://github.com/ACHinrichs/emacs-config)

Thanks for your help

**Comment by ACHinrichs** [comment]
Apparently the slow-on-windows bug is already known (#252), sorry about that.
My version NeoTree version is displayed in the package-list as `20170522.758`

**Comment by sdwolf** [comment]
You can try and debug segfaults folowing the instructions from here:
https://github.com/syl20bnr/spacemacs/wiki/Debugging#debugging-segmentation-faults-with-gdb.

**Comment by ACHinrichs** [comment]
```
Thread 1 "emacs" received signal SIGSEGV, Segmentation fault.
normal_char_ascent_descent (font=0x0, c=c@entry=-1, 
    ascent=ascent@entry=0x7ffd0dfa957c, descent=descent@entry=0x7ffd0dfa9580)
    at xdisp.c:25008
25008	  *ascent = FONT_BASE (font);
```

**Comment by Abdisalan** [comment]
Closing as stale. If you're still experiencing this, please open a new issue.
