### ISSUE TITLE
Feature: Don't reset size after open

### ISSUE THREAD

**Issue by torgeir** [jaypei/emacs-neotree#262]
As suggested in https://github.com/jaypei/emacs-neotree/issues/103#issuecomment-284211987 

> When I adjust to drag neotree size; then click to open some file; neotree window size will be reset, how to disable this behaviour?

Edit: The temporary solution in https://github.com/jaypei/emacs-neotree/issues/262#issuecomment-383352799 works like a charm.

**Comment by torgeir** [comment]
This seems to do the trick..

```
    (defun t/neotree-keep-size (fn &rest args)
      "Reset neotree width after open, if user adjusted it's size."
      (let ((w (window-width)))
        (funcall fn)
        (neo-global--set-window-width w)))
    (advice-add 'neotree-enter :around 't/neotree-keep-size)
```

**Comment by Moghul** [comment]
This was posted quite some time ago, but here I am, and this doesn't work for me.

Pasted this snippet into my .emacs file and restarted emacs. Pressed f8, clicked a file, widened the frame, clicked another file aaaaand... it reset. Not sure what to do here.

**Comment by torgeir** [comment]
Yeah, it's by far not an optimal solution. For me it still works ok, though, as long as you navigate to the neotree window with they keyboard, and don't close and reopen the neotree window between opening files. Clicking a file with the mouse resets the width on my end as well, maybe it calls some another function?

**Comment by Moghul** [comment]
Super new to emacs so your guess is better than mine.

**Comment by didibus** [comment]
What causes this is the `neo-window--zoom` function. On `'minimize` it will set the window width of neotree back to the default.

So if you override that function, you won't have the width be reset when you open a file in neotree:

```
  ;; Override a neotree.el fn so that it does not reset the neotree window
  ;; width after you open another file by clicking or using RET on it from
  ;; within neotree.
  (eval-after-load "neotree"
    '(defun neo-window--zoom (method)
       "Zoom the NeoTree window, the METHOD should one of these options:
'maximize 'minimize 'zoom-in 'zoom-out."
       (neo-buffer--unlock-width)
       (cond
        ((eq method 'maximize)
         (maximize-window))
        ((eq method 'minimize)
         (message "neotree override: its window width will not be reset"))
        ((eq method 'zoom-in)
         (shrink-window-horizontally 2))
        ((eq method 'zoom-out)
         (enlarge-window-horizontally 2)))
       (neo-buffer--lock-width)))
```

**Comment by didibus** [comment]
Alright, here is the perfect fix, which solves neotree resetting the width back to default in all cases:

```lisp
  ;; Set the neo-window-width to the current width of the
  ;; neotree window, to trick neotree into resetting the
  ;; width back to the actual window width.
  ;; Fixes: https://github.com/jaypei/emacs-neotree/issues/262
  (eval-after-load "neotree"
    '(add-to-list 'window-size-change-functions
                  (lambda (frame)
                    (let ((neo-window (neo-global--get-window)))
                      (unless (null neo-window)
                        (setq neo-window-width (window-width neo-window)))))))
```

**Comment by Moghul** [comment]
Thank you very much for the fix! I'm sorry if this is a stupid question, but is this meant to go into the .emacs file?

(again, still new to emacs)

**Comment by torgeir** [comment]
@didibus Works like a charm!
@Moghul Yes.

**Comment by pbgc** [comment]
@jaypei this should be standard in NeoTree! @didibus solution above works like a charm! and neotree its a LOT more useful is we can alter it's width !

**Comment by pbgc** [comment]
@palikar Like I said in the comment before ... the solution by @didibus above works really great and it's really usefull!! I use it without any problem for a really long time! 
Don't you think that this should be an option in neotree or at least be in the documentation ? 
I see it asked in several places ... like here https://emacs.stackexchange.com/questions/37678/neotree-window-not-resizable whereI pointed to this solution.

**Comment by palikar** [comment]
@pbgc  thanks for bringing the issue to my attention. I myself found this "feature" of neotree annoying. The fix of @didibus  is, however, kind of a hack. I looked into the code and I've implemented a custom that cat toggle the behavior. Pushing it now ( https://github.com/jaypei/emacs-neotree/commit/6e3ae07b08d4dd218c119e91a101d7e7ed6ef4d9 ). Be sure to open a new issue if there are problems with the new version.

**Comment by didibus** [comment]
@palikar Your fix addresses the issue described by OP, by the neotree width is still reset when neotree is closed and re-opened. In my case, I don't want anything to ever reset the neotree size, I want to manually adjust the size, and have it stay to my own manual size until I manually resize it again. For that, my fix still works, but your patch doesn't.
