### ISSUE TITLE
NeoTree crashes when navigating to missing parent

### ISSUE THREAD

**Issue by opyate** [jaypei/emacs-neotree#265]
Potential bug? In Spacemacs, I opened a file in a sub directory, then launched NeoTree. In the shell, I delete the subdirectory. Back in NeoTree, I press `K` to go to the parent, which gives an error message in the [echo area](http://www.gnu.org/software/emacs/manual/html_node/emacs/Echo-Area.html#Echo-Area) but also hangs Spacemacs.

**Comment by sdwolf** [comment]
If the editor hangs, try the steps in the following link to get a backtrace:
https://github.com/syl20bnr/spacemacs/wiki/Debugging#debug-a-freezing-instance

**Comment by opyate** [comment]
@sdwolf thanks for the `kill -12 $PID` tip.

I've been struggling to recreate this, so it might be unrelated to my described actions (deleting a folder which is being browsed in Neotree, which helpfully says `Walk directory "a/b" failed.`

Closing for now.

**Comment by opyate** [comment]
Ha! After previous `Walk directory` messages I could go on with my work, but this time it hung/hanged.

BRB with stacktrace.

**Comment by Abdisalan** [comment]
Closing as stale. If you're still experiencing this, please open a new issue.
