### ISSUE TITLE
Any means to hide the slash (/) trailing the directories?

### ISSUE THREAD

**Issue by ZaenChou** [jaypei/emacs-neotree#266]
I guess this might be a pretty niche issue, but I'm not very comfortable with the '/' following the directories, since I already know they are directories from the color.
Is there any trigger to hide that? Or, any ideas where to look for in the codes? many thanks ❤️

**Comment by lukertty** [comment]
Add this to your init file:

```elisp
(defun neo-buffer--insert-dir-entry (node depth expanded)
  (let ((node-short-name (neo-path--file-short-name node)))
    (insert-char ?\s (* (- depth 1) 2)) ; indent
    (when (memq 'char neo-vc-integration)
      (insert-char ?\s 2))
    (neo-buffer--insert-fold-symbol
     (if expanded 'open 'close) node)
    (insert-button node-short-name ;; (concat node-short-name "/")
                   'follow-link t
                   'face neo-dir-link-face
                   'neo-full-path node
                   'keymap neotree-dir-button-keymap
                   'help-echo (neo-buffer--help-echo-message node-short-name))
    (neo-buffer--node-list-set nil node)
    (neo-buffer--newline-and-begin)))
```

**Comment by ZaenChou** [comment]
Thank you very much for the code, and your precious time.
Though unfortunately, it didn't work out, on both icon theme and ascii.
Could you let me know whether you brought the code from somewhere else or you wrote it (!). thanks

**Comment by lukertty** [comment]
@ZaenChou 

The code is from:
https://github.com/jaypei/emacs-neotree/blob/bc98dfb44c106375efa4f26848f3790ee264da97/neotree.el#L1369

Can you try this:
1. emacs -Q
2. paste these to emacs **(change dir to your local neotree path)**
3. M-x eval-buffer
4. M-x neotree

```elisp
(add-to-list 'load-path "/Users/lukertty/.emacs.d/elpa-25.2.1/neotree-20170522.758")
(require 'neotree)
(defun neo-buffer--insert-dir-entry (node depth expanded)
  (let ((node-short-name (neo-path--file-short-name node)))
    (insert-char ?\s (* (- depth 1) 2)) ; indent
    (when (memq 'char neo-vc-integration)
      (insert-char ?\s 2))
    (neo-buffer--insert-fold-symbol
     (if expanded 'open 'close) node)
    (insert-button node-short-name ;; (concat node-short-name "/")
                   'follow-link t
                   'face neo-dir-link-face
                   'neo-full-path node
                   'keymap neotree-dir-button-keymap
                   'help-echo (neo-buffer--help-echo-message node-short-name))
    (neo-buffer--node-list-set nil node)
    (neo-buffer--newline-and-begin)))
```

**Comment by ZaenChou** [comment]
@lukertty 
OHOHOHOHOH
After trying your method above and succeeded, I found out that my failure had everything to do with spacemacs' unique way of configuring packages. Very sorry.
Do you think it would be good to post the code to neotree-wiki or somewhere else? of course, you did the excellent job, if you want me to post it, i would humbly give you all the credits.

**Comment by lukertty** [comment]
@ZaenChou 
Nonono，the only thing i do is change `(concat node-short-name "/")` to `node-short-name`...

**Comment by ZaenChou** [comment]
@lukertty you're right, but even a small (sorry) wit like that can help a lot of people, i believe.
anyway, as you wish. Again, huge thanks!!

**Comment by ZaenChou** [comment]
oops, forgot to close
