### ISSUE TITLE
Cut, Copy, Paste.

### ISSUE THREAD

**Issue by feluxe** [jaypei/emacs-neotree#267]
Hi there,

thanks for making Neotree happen! :-)

I have one suggestion. Today I had to move a bunch of files across multiple directories. I used the "copy" [C] shortcut a lot and I was thinking: It would be awesome if there was a "cut" [x] shortcut and a "paste" [v] shortcut. It would be way easier to move files around like that. What do you think?
_

**Comment by zw963** [comment]
I think if we can operation with `mouse-1`, just like most other editor file navigator bar does,
it will awesome, anyway, sometimes, use mouse is handy.

**Comment by Abdisalan** [comment]
Closing as stale. If you'd still like this feature, please make a new issue
