### ISSUE TITLE
Highlight current file

### ISSUE THREAD

**Issue by creack** [jaypei/emacs-neotree#268]
Hello,

Is there a way to have neotree highlight the active buffer in the tree?

**Comment by rifazn** [comment]
This will certainly be very useful.

**Comment by scottgerring** [comment]
I'm also interested in this 2 years down the road. Has anything changed?

**Comment by jcs090218** [comment]
I wonder is this package still maintained? If not, I think there would be many people willing to maintain this package! :(

**Comment by jcs090218** [comment]
ping @jaypei
