### ISSUE TITLE
Feature request for something similar to :NERDTreeFind

### ISSUE THREAD

**Issue by agsdot** [jaypei/emacs-neotree#27]
Hi Zhen Pei,

Thanks for building this project!  Neotree looks like it has a lot of potential!

I'd like to request that a feature similar to :NerdTreeFind be built into Neotree--find the current file in the sidebar.

In the Vim world, it's one of the differentiators that helps it to stand out.  http://www.reddit.com/r/vim/comments/22ztqp/why_does_nerdtree_exist_whats_wrong_with_netrw/cgs2hxv 

Thanks!

Jonathan Lai

**Comment by agsdot** [comment]
Hi Zhen Pei,

I've noticed that recently, in the past month (because of recent git commits? I don't know), that neotree-find identifies and highlights the file of interest, but if I navigate to other files and select them, the files do not open.

Do you have any ideas of what may be casuing this?

**Comment by jaypei** [comment]
Hi agsdot,

This sounds like a bug, but I didn't reproduce it.
Can you give me more details?

**Comment by agsdot** [comment]
Hi Zhen Pei,

Hum....I think its an issue with my configs. I looked through my .emacs.d and slowly stripped back configuration layers.  When I removed my evil / vim configurations, neotree started behaving as expected.  Later this evening/later this week I'll go thru the evil configs line by line to find it out.

Sorry about that.  Once I figure it out, I'll report back here what happened.
