### ISSUE TITLE
is there a "collapse all folders" command?

### ISSUE THREAD

**Issue by ninrod** [jaypei/emacs-neotree#277]
As the title says. Frequent use case for me.

**Comment by vineethkartha** [comment]
I have a fix for this issue

**Comment by Difrex** [comment]
@vineethkartha, can you share it?

**Comment by rubynho** [comment]
I would like to have this feature too 🙂.

**Comment by vineethkartha** [comment]
https://github.com/jaypei/emacs-neotree/pull/280 this I believe has already been merged
