### ISSUE TITLE
Open new file in split window/buffer

### ISSUE THREAD

**Issue by r3j3c73d** [jaypei/emacs-neotree#282]
Hi, Thank you for neotree, it's very useful.
I was thinking about how it works and I have a suggestion:
When we want to open a file, if it can be opened in split window/buffer it would be very helping

**Comment by Jonathas-Conceicao** [comment]
While on Neotree buffer you can open file with a vertical or horizontal frame split. Just use:
  `|` to slip vertically and open the file.
  `-` to split horizontally and open the file.

**Comment by Abdisalan** [comment]
This looks resolved. Closing
