### ISSUE TITLE
Annoying behavior after creating a new file using neotree 

### ISSUE THREAD

**Issue by dineshbhosale** [jaypei/emacs-neotree#284]
In Neotree `-` opens the selected buffer in a split window below the current one, and `|` opens it in a split window to the right.

This is useful but when you create a new file, it automatically opens it in the first buffer without asking or pressing anything.

Neotree should not open newly created file in the first buffer and instead allow the programmer to open it manually in a different position using `-` or `|` and not in the first buffer.

When you are editing buffer A and you create a new file B using Neotree, all of a sudden first buffer (buffer A) is sent in background and replaced with buffer B, then you have to switch back to buffer A to continue editing, it gets in the flow and it is really annoying.

Is there any way we can stop neotree from opening a new buffer when you create a new file ?

A custom variable? A toggle function ? something that I can use to stop Neotree from automatically opening newly created file in first buffer.

**Comment by sdwolf** [comment]
Add this in your `dotspacemacs/user-config `:
```emacs-lisp
(setq neo-create-file-auto-open nil)
```

**Comment by dineshbhosale** [comment]
Thanks a lot !!!!
