### ISSUE TITLE
How should I know neotree is on?

### ISSUE THREAD

**Issue by XiaofanLinUS** [jaypei/emacs-neotree#285]
Hi, I want to set up a key binding that once a combo of keys is pressed,
If neotree is off, neotree-dir is called to type in the directory root.
else if neotree is on, neotree-toggle is called to turn of neotree.
I try to adopt [this approach](https://stackoverflow.com/questions/1511737/how-do-you-list-the-active-minor-modes-in-emacs).
But  (bound-and-true-p neotree-mode) returns false everytime.
Here is my code:
```
(defun neo-toggle ()
  (interactive)
  (if (bound-and-true-p neotree)
      (neotree-toggle)
    (call-interactively 'neotree-dir)))
```
I am new to lisp. 
Any suggestion would be great.
Thanks.

**Comment by tttuuu888** [comment]
Below code will work as you expected.

```
(defun neo-toggle ()
  (interactive)
  (if (and (fboundp 'neo-global--window-exists-p)
           (neo-global--window-exists-p))
      (neotree-toggle)
    (call-interactively 'neotree-dir)))
```

I hope this would be helpful.

**Comment by Abdisalan** [comment]
Closing because this looks resolved
