### ISSUE TITLE
emacs alway show "File not found in root path, do you want to change root?" while neo-autorefresh is on.

### ISSUE THREAD

**Issue by chenpoyang** [jaypei/emacs-neotree#286]
i customize the variable neo-autorefresh, and set it to "t".
then i open a file and open neotree at the same time, it refresh the tree base on the current buffer.
what annoy me is that:
i have a file open in the buffer and toggle the neotree at the same time.
then i try to open another file by:helm-find-files(C-x C-f), when i finish typing "C-x C-f", then stop for a while. an emacs prompt window annoy me by saying: "File not found in root path, do you want to change root?" if i click yes: the neotree will switch to $HOME directory. if i click no: it will not refresh the directory tree.
how to avoid changing root while there is no file open(in helm-find-files buffer status).

**Comment by palikar** [comment]
With the advice of @NeQuissimus  and since f66e8be792af2bd1cc28308fda2901e2f4d02c91 this problem should be solved. I've also made the `neo-force-change-root` non-nil by default so the annoyance should be minimized.
