### ISSUE TITLE
Close parent of node

### ISSUE THREAD

**Issue by birnam** [jaypei/emacs-neotree#293]
I'm trying to bring over an oft-used mapping from NerdTree, where 'x' will automatically close the parent of a node. Our NeoTree equivalent seems to be two 'h's, one to go up to parent and the other to perform the collapse.

Is there a way to bind this for now? I'm new to emacs/spacemacs/neotree and my lisp-fu is still pretty light.

**Comment by wallfile** [comment]
```elisp
(defun neotree-close-parent ()
  "Close parent directory of current node."
  (interactive)
  (neotree-select-up-node)
  (let* ((btn-full-path (neo-buffer--get-filename-current-line))
         (path (if btn-full-path btn-full-path neo-buffer--start-node)))
        (when (file-name-directory path)
          (if (neo-buffer--expanded-node-p path) (neotree-enter))))
```
Setting up the keybinding with `general` (and `use-package`):
```elisp
(use-package neotree
  :ensure t
  :config
  (general-define-key
    :keymaps 'neotree-mode-map
    "x" 'neotree-close-parent))
```

**Comment by birnam** [comment]
excellent, this works great! (seems to need a fifth close paren after neotree-enter though) 

many thanks. I'll have to check out use-package and general further, they seem handy.
