### ISSUE TITLE
Error occurs when do `neotree-show' - Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by jcs090218** [jaypei/emacs-neotree#295]
The full error is: 
`cond: Wrong type argument: stringp, nil` when I call `neotree-show` command.

Not pretty sure why this occurs..

**Comment by palikar** [comment]
It works fine by me. Can you elaborate? Do you have something weird in your neotree configuration? Does the error persists when you call the function manually with `M-x neotree-show`?

**Comment by jcs090218** [comment]
I don't think is the my configuration's issue because even I get ride of all my configuration for neotree, the error still remain. I tried reinstall and recompile the package but it did not works. Otherwise neotree seems to work in previous version then until now it is no longer working anymore. Here is some information about my environment, hopefully these will help?

Emacs Version: `25.2`, `26.1` (Both does not work)
Operating System: `Windows 10`, `Ubuntu`, `MacOS` (All of them does not work)
neotree version: `newest`

**Comment by jcs090218** [comment]
I think the issue has been fixed! Thanks!
