### ISSUE TITLE
Window behavior different with Emacs 26.1

### ISSUE THREAD

**Issue by normano64** [jaypei/emacs-neotree#296]
Hi, after I updated to Emacs 26.1 the neotree window is getting closed when I do `C-x 1` which it didn't do in previous Emacs.

I did find a solution to the problem, by setting the window parameter `no-delete-other-windows` to true,
but I'm not sure about doing a PR as it may change or break old behavior.

```elisp
(defun neo-window--init (window buffer)
  "Make WINDOW a NeoTree window.
NeoTree buffer is BUFFER."
  (neo-buffer--with-resizable-window
   (switch-to-buffer buffer)

   ;; Adding this line will make the window fixed
   (set-window-parameter window 'no-delete-other-windows t)
   ;;

   (set-window-dedicated-p window t))
  window)
```
Is it possible to have this added to emacs-neotree? :smile:

**Comment by jaypei** [comment]
Thanks @normano64
