### ISSUE TITLE
Invalid image type ‘xpm’

### ISSUE THREAD

**Issue by WellRedPandit** [jaypei/emacs-neotree#299]
# The problem

Running Emacs 25.3.1 on Ubuntu 16.04

Command `(neo-global--open-dir "/home/wrp/org")` causes `error: Invalid image type ‘xpm’` in the Warnings buffer 

Also i see `Error running timer 'neo-global--do-autorefresh': (error: "Invalid image type ‘xpm’")` in the minibuffer

# Questions
1. how to solve the xpm error without disabling neotree
2. how to disable autorefresh

Thank you!

**Comment by esguti** [comment]
I solved the problem compiling emacs with xpm support. For that I have installed these libraries:

```bash
sudo apt-get install build-essential texinfo libx11-dev libxpm-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev libgtk-3-dev libncurses-dev libgnutls28-dev
```
Then configure & make & sudo make install.

```bash
./configure
make
sudo make install
```

More info about compilation [here](https://askubuntu.com/questions/213873/what-libraries-do-i-need-to-install-if-i-want-to-compile-emacs)

Regards

**Comment by Abdisalan** [comment]
Closing as stale. If you're still experiencing this, please open a new issue.
