### ISSUE TITLE
Unable to copy file: already exists

### ISSUE THREAD

**Issue by martijnjanssen** [jaypei/emacs-neotree#302]
On linux, when trying to copy a file, I get the already exists message. I'm trying to create the file `config.toml`, but it is clashing with another file named `config.toml.bak`. If there is a  file that has the same name, but with a double extension, the error occurs.

**Comment by palikar** [comment]
Yep, I can reproduce this. I will see what can I do.

**Comment by palikar** [comment]
Upon further investigation, I think there is no bug here. Is it possible that you are actually selecting the wrong thing. When copying, if you start typing the name of the destination file, helm kinda prompts you to select the existing in the directory file. It's easy then to hit enter on this file and not on the non-existing thing (the actual destination that you want). Make sure to select the file that is non existent in the helm prompt. I think the entry should be prefixed with `[?] `
Here is a screenshots illustrating what I mean:
![screenshot from 2018-11-08 23-53-47](https://user-images.githubusercontent.com/11386449/48232481-18873c80-e3b2-11e8-906e-2f7fb2eaee17.png)

**Comment by martijnjanssen** [comment]
Ah, that does make sense. Thanks!

**Comment by palikar** [comment]
Cool. Glad to help.
