### ISSUE TITLE
Add option to disable footer

### ISSUE THREAD

**Issue by TyOverby** [jaypei/emacs-neotree#304]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/573215/45577159-77f02280-b82f-11e8-8790-746ad0015c09.png">

^ This part

**Comment by Anntoin** [comment]
That can be disabled by setting `neo-mode-line-type` to none, see the other options here:
https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el

**Comment by palikar** [comment]
As pointed out by @Anntoin this feature is already available.
