### ISSUE TITLE
Scroll position resets when autorefresh is on

### ISSUE THREAD

**Issue by arnemart** [jaypei/emacs-neotree#305]
When scrolling with the mouse in neotree trying to find the correct file to open, the scroll position resets to show the currently open file after a short time. This is a little annoying, the only workaround I have found is to click somewhere on the left side of the files to move the cursor. Is there a way to avoid this behavior without disabling autorefresh?

**Comment by Abdisalan** [comment]
Closing as stale. If you're still experiencing this, please open a new issue.
