### ISSUE TITLE
Recent update disabled neotree and it won't work unless all-the-icons is disabled

### ISSUE THREAD

**Issue by yilkalargaw** [jaypei/emacs-neotree#308]
After updating neotree recently I keep getting a warning "function's definitinon is nil" when ever I try to use neotree.  It only works when I change:
```elisp
(setq neo-theme (if (display-graphic-p) 'icons 'arrows))
```
into 

```elisp
(setq neo-theme 'arrows)
```
Every thing goes back to normal when returning to an older version.

**Comment by palikar** [comment]
Hi @yilkalargaw,

could this be the problem in #307?

**Comment by palikar** [comment]
OK, I've made a new commit on the dev branch that should fix the issue. Could you try it out and let me know if the problem persists.

**Comment by yilkalargaw** [comment]
Now it works. Thanks. I am closing the issue hopping that changes will soon be would be  merged to master.  Really soon.
