### ISSUE TITLE
Last update broke projectile integration

### ISSUE THREAD

**Issue by pbgc** [jaypei/emacs-neotree#310]
@palikar 

Hi,

Just updated to lates MELPA dev release and projectile integration broke bad!

After opening a project (projectile + perspective) neotree displays the project (vc = git) but if I run "neotree-project-dir" (that I have bounded to F8) to hide the project, when invoking "neotree-project-dir" again ... it takes almost A MINUTE to open (emacs freezes) and then open the folder where the buffer file is and not the root of the project, as before.

EDIT: neotree-project-dir is like in the docs:
```
(defun neotree-project-dir ()
    "Open NeoTree using the projectile."
    (interactive)
    (let ((project-dir (projectile-project-root))
          (file-name (buffer-file-name)))
      (neotree-toggle)
      (if project-dir
          (if (neo-global--window-exists-p)
              (progn
                (neotree-dir project-dir)
                (neotree-find file-name)))
        (message "Could not find vc project root."))))
```

**Comment by pbgc** [comment]
this only happens after https://github.com/jaypei/emacs-neotree/commit/ee3f508f8cc854c96e7845e5ccbd86cf88cbbfe7

**Comment by palikar** [comment]
Hi @pbgc ,
thanks fro the feedback. I did't think that the change would cause trouble but oh well. Is the project that you try to open really big(number of files)? Is the problem there also for smaller projects (with fewer files)?

**Comment by pbgc** [comment]
@palikar it's big but not huge.
With smaller projects it's faster (but noticeable slower than before) and what is opened, after closing and reopen, in neotree is the folder where the buffer file is and not the root of the project!

**Comment by palikar** [comment]
@pbgc sorry for the late response. I've reverted the change now. Let me know if there are problems again. You can check out #279 for a little more information on the change and what I was trying to "fix".

**Comment by pbgc** [comment]
@palikar ok, everything went back to "normal"! thanks!!
