### ISSUE TITLE
How can I create a new directory in neotree?

### ISSUE THREAD

**Issue by SysConKonn** [jaypei/emacs-neotree#315]
I found that I don't know how to create a directory in neotree and it seems that I haven't found any hint about it in neotree help page.

**Comment by phoe** [comment]
This functionality should be added to neotree. It is possible to create files, but impossible to create directories, and I see no reason for that omission.

**Comment by palikar** [comment]
@phoe,  @SysConKonn you **can** create directory. Just start creating a regular file and put a trailing slash at the end. Neotree will then interpret this as new directory. To be clear, to create new directory, you will have to type something like `~/new_dir/` in the new file prompt of neotree

**Comment by jdl** [comment]
I vaguely recall that the trailing slash worked for creating a directory in the past, but it doesn't seem to do so now. If I type `c` -> `~/new_dir/` -> `y` I end up with a file named `new_dir`.

**Comment by yangruihan** [comment]
> I vaguely recall that the trailing slash worked for creating a directory in the past, but it doesn't seem to do so now. If I type `c` -> `~/new_dir/` -> `y` I end up with a file named `new_dir`.

It work.  

version 20200324.194

**Comment by verificationcontractor** [comment]
C-c C-n then add a slash after the filename and it will create a directory.

**Comment by oreillyross** [comment]
typing the char **a** when neotree is open and active then opens up a dialog where you can create a new file or new directory. To create a new directory make sure to leave a trailing slash.
