### ISSUE TITLE
Make a new release on MELPA stable

### ISSUE THREAD

**Issue by arankaren** [jaypei/emacs-neotree#317]
Hi, on MELPA stable last release is `v0.5.2 `that was 1 years ago, since then a lot of features have been added to the project, such features are not available when downloading via MELPA stable which is a recommended distribution channel to use in most of the Emacs packages.

Please, with the new release, the errors are fixed eg. `autorefresh`.

Thanks.

**Comment by DivineDominion** [comment]
@palikar Do you need help pushing this forward?

**Comment by sten0** [comment]
@jaypei and @palikar,

Tagging a new stable release before Christmas would be much appreciated!  In Debian we have 0.5.2, the freeze for the next stable release is approaching, and our Debian Stable users will be stuck with this version for the next two years unless a release is made.

Thanks!
Nicholas

**Comment by Abdisalan** [comment]
Seems too late but I can look into making a new release with what's in the repo right now

**Comment by Abdisalan** [comment]
Made a new release of version 0.6.0 https://github.com/jaypei/emacs-neotree/releases/tag/0.6.0

**Comment by DivineDominion** [comment]
Great to see this, thanks @Abdisalan!

**Comment by sten0** [comment]
> Seems too late but I can look into making a new release with what's in the repo right now

Better late than never!

> Made a new release of version 0.6.0 https://github.com/jaypei/emacs-neotree/releases/tag/0.6.0

Thanks!
