### ISSUE TITLE
Allow adding hidden files/directories regex

### ISSUE THREAD

**Issue by teeann** [jaypei/emacs-neotree#323]
1. `neotree` does not hide default files/directories of some IDEs, e.g `__pycache__` in `PyCharm`. 
 2. It would be nice if `neotree` adds support for managing hidden files regex signatures.

**Comment by toyboot4e** [comment]
Actually you can:

```elisp
(setq neo-hidden-regexp-list
    '("^\\." "\\.cs\\.meta$" "\\.pyc$" "~$" "^#.*#$" "\\.elc$" ;; defaults
      ;; add yours:
      "__pycache__"))
```elisp

**Comment by teeann** [comment]
Thank you! I didn't know this feature
