### ISSUE TITLE
Git mv when in a git repo

### ISSUE THREAD

**Issue by Chocrates** [jaypei/emacs-neotree#324]
Would it be possible to configure this plugin to run a `git mv` instead of a (presumably) shell `mv` if I am in a git repo when renaming a file?

**Comment by bkaestner** [comment]
Sure thing, @Chocrates , one can use `vc-rename-file` instead of `rename-file`. Given the current activity on the repository, you might want to apply #338 to your own copy of Neotree (if you're still an active user).

**Comment by Chocrates** [comment]
Thanks for looking at this @bkaestner!  Yeah I'm not using emacs these days :(
