### ISSUE TITLE
"apply: Symbol’s function definition is void: nil" when using 'icons theme and trying to go to root folder

### ISSUE THREAD

**Issue by srj-github** [jaypei/emacs-neotree#325]
I'm using Windows and the error only appears when using the icons theme and trying to go to any root folder (C:/, D:/, etc.).

It's working for any other theme. Not sure if the issue is with 'all-the-icons' or neotree.

**Comment by Abdisalan** [comment]
Closing as stale. If you're still experiencing this, please open a new issue. I'm curious what could be causing this
