### ISSUE TITLE
Can't resize neotree window through mouse drag

### ISSUE THREAD

**Issue by weavejester** [jaypei/emacs-neotree#327]
When I try to resize the neotree window by dragging the edge with my cursor, it often tries to resize back to the default width, as if it's intercepting a resize event and overriding. Sometimes this behavior goes away at random.

I assume this is a bug, but I haven't been able to track it down, or figure out a workaround. I'm using Emacs 26.3 on MacOS (the latest railwaycat "emacs-mac" build, if that matters).

**Comment by weavejester** [comment]
Interestingly once the resizing behavior stops, it doesn't come back until Emacs is restarted, and it also fixes an issue where neotree interferes with the modeline of other windows.

**Comment by philipsd6** [comment]
When I try to resize it with my mouse, I just see the message "No resizable window on the left of this one." But I just use `A` in the active neotree sidebar when I see to see more.

**Comment by weavejester** [comment]
If you set `(setq neo-window-fixed-size nil)`, then the no resizeable window message disappears. However, for some reason it still tries to enforce a fixed size. Using `A` has the same effect for me: it resizes for a split second, then immediately flicks back to the default width (at least I assume it's the default width).

Every so often I'll try to track down this bug, or work out what causes it, but still I haven't been able to figure out the particular combination of actions that fixes Neotree's sizing bug. Presumably it's somehow interacting with either my build of Emacs or some extension in a weird way, but attempts to narrow down the cause have proven fruitless thus far.

**Comment by Abdisalan** [comment]
> When I try to resize the neotree window by dragging the edge with my cursor, it often tries to resize back to the default width, as if it's intercepting a resize event and overriding. Sometimes this behavior goes away at random.
> 
> I assume this is a bug, but I haven't been able to track it down, or figure out a workaround. I'm using Emacs 26.3 on MacOS (the latest railwaycat "emacs-mac" build, if that matters).

Are you still running into this issue? Also, are you able to recreate the issue with `emacs -q -l path/to/neotree.el` ?

**Comment by weavejester** [comment]
Since raising the issue I've switched from MacOS to Linux, and under Linux I haven't seen the issue occur from Emacs 28 onward.

**Comment by henriquesebastiao** [comment]
This problem occurred for me with Emacs 30.1, but setting `(setq neo-window-fixed-size nil)` solved the problem.
