### ISSUE TITLE
[Question] What is difference between neotree-rename-node and neo-buffer--rename-node

### ISSUE THREAD

**Issue by conao3** [jaypei/emacs-neotree#333]
What is the difference between `neotree-rename-node` and `neo-buffer--rename-node`?

Also, in general, two hyphens indicate an internal function and are not intended to be invoked by the user as an interactive function.
Not following the package prefixing rule called `neo-` is also a problem, as warned by [package-lint](https://github.com/purcell/package-lint).

**Comment by Abdisalan** [comment]
There doesn't seem to be any functional difference. This'll be noted for any future refactors, including the package prefixing rule.
