### ISSUE TITLE
Shorten the "autorefresh" delay/timer?

### ISSUE THREAD

**Issue by ianyepan** [jaypei/emacs-neotree#341]
I'd like to make the autorefresh happen more frequently. At the moment I am observing a couple of seconds of delay when the file tree updates.
What is the best practice to set the timer? And if I set it to a small number (maybe 0.1 sec), would it have a large impact on my Emacs performance?
Cheers!

**Comment by ianpan870102** [comment]
Friendly ping :-)

**Comment by ianyepan** [comment]
I found the solution: inside the function definition of `neo-global--attach`, change the arguments of `run-with-idle-timer` from `2, 10` to `0.01 t` to simulate "instant change".

```emacs-lisp
(defun neo-global--attach ()
  "Attach the global neotree buffer"
  (when neo-global--autorefresh-timer
    (cancel-timer neo-global--autorefresh-timer))
  (when neo-autorefresh
    (setq neo-global--autorefresh-timer
          (run-with-idle-timer 0.01 t 'neo-global--do-autorefresh)))
  (setq neo-global--buffer (get-buffer neo-buffer-name))
  (setq neo-global--window (get-buffer-window
                            neo-global--buffer))
  (neo-global--with-buffer
    (neo-buffer--lock-width))
  (run-hook-with-args 'neo-after-create-hook '(window)))
```
