### ISSUE TITLE
[Question] all the icons theme doesn't work in no-window mode?

### ISSUE THREAD

**Issue by ketaro-m** [jaypei/emacs-neotree#346]
Having installed [all-the-icons](https://github.com/domtronn/all-the-icons.el) package and its fotns, the icons are shown up on the tree. However, it doesn't work in no-window emacs mode (launching by "emacs -nw"). Is there any way to solve it?

**Comment by Abdisalan** [comment]
Looks like all-the-icons does not work in terminal mode of emacs. I looked in the installation instructions they want you to make sure that you're using a graphics display (not a terminal display)  https://github.com/domtronn/all-the-icons.el#installation

```elisp
(when (display-graphic-p)
  (require 'all-the-icons))
```
