### ISSUE TITLE
How turn up to pen drive?

### ISSUE THREAD

**Issue by eudavidcesar** [jaypei/emacs-neotree#347]
I can't see how the Neo Tree could open my pendrive files. I use my pendrive constantly but how I can made my pendrive open in Neo Tree?

**Comment by Atlas48** [comment]
Ask stackoverflow, not here.

**Comment by Abdisalan** [comment]
neotree can see your file system already, it could be that you haven't navigated to your pen drive?

**Comment by azzamsa** [comment]
I think we can safely close this 2 years old issue.

**Comment by Abdisalan** [comment]
I like to give people at least some chance. But yeah, I'll close this one
