### ISSUE TITLE
Is neotree unmaintained

### ISSUE THREAD

**Issue by Ergus** [jaypei/emacs-neotree#351]
Hi:

I see neotree haven't received any update in almost 3 years... is it somehow abandoned?

**Comment by jaypei** [comment]
Yes, I have started a new job and don't have the energy to continue updating this project. Are you
interested in taking over maintenance?

**Comment by Ergus** [comment]
Hi:
Sorry to hear that. Sadly I cannot adopt it either (also new job here). I asked just because I was developing a small plugins for dired and I considered if I should also provide some support for neotree.

However, in the long path maybe I will consider to check is some of the nice neotree's features could be implementes or attached to dired...

**Comment by jaypei** [comment]
@Abdisalan I am glad to hear this news. I have already invited you to the developer list. Looking forward to
you bringing new features to the project. If you have any questions, you can email me.  

jaypei97159@gmail.com
