### ISSUE TITLE
neotree underlined filenames

### ISSUE THREAD

**Issue by ethancobos** [jaypei/emacs-neotree#352]
Has anyone ever had this behavior from neotree? Im using doom emacs and no matter how many different ways I try to change the neotree theme, I'm always left with no file icons and weird underlines under each filename. even the following line does absolutely nothing:

(setq neo-theme (if (display-graphic-p) 'icons 'arrow))

I'm very confused as I cannot find an example of this behavior replicated anywhere.

<img width="504" alt="Screenshot 2023-08-06 at 11 34 11 AM" src="https://github.com/jaypei/emacs-neotree/assets/90016437/73a82f88-c760-49df-b438-4fb55ef5c4ad">

**Comment by Abdisalan** [comment]
That's caused by doom emacs I believe. Try this in your config

```elisp
(setq doom-themes-neotree-file-icons t)
```
