### ISSUE TITLE
Open file in the upmost pane

### ISSUE THREAD

**Issue by verificationcontractor** [jaypei/emacs-neotree#353]
I have 2 panes split horizontally and if the one below is selected then clicking on a file in neotree opens it in the lower pane. I would like it to be opened in the upper pane. There should be a dedicated pane for the files. Simetimes I work in SLIME and I like my SLIME REPL to be at the bottom and not to be replaced with a file editing pane when I click on a file in neotree.

**Comment by Abdisalan** [comment]
By default neotree opens the file in the most recently used window. You can try to click on the upmost pane first before clicking on a file in neotree.

You could also try installing `ace-window` package and using this function `neo-open-file-ace-window`. It should let you choose the window you open the file in. The shourtcut is `a` when your cursor is over a file in the neotree buffer


https://github.com/jaypei/emacs-neotree/blob/2b0cb8285352202c62b1e46a8aa265a5e4f9d966/neotree.el#L1886-L1889
