### ISSUE TITLE
Peep-mode

### ISSUE THREAD

**Issue by mijoharas** [jaypei/emacs-neotree#46]
I would like to suggest a "Peep-mode" or some such thing similar to Sublime Text where you can get an instant preview of the file just by scrolling. See [`peep-dired`](https://github.com/asok/peep-dired) for one such implementation. (N.B. for peep-dired the temporary buffers continue to hang around rather than being ephemeral like in Sublime Text.)

**Comment by arronmabrey** [comment]
Hey guys, has any progress been made in this area? I was just looking for something like this to use inside spacemacs. I have yet to do any elisp development, but I have worked with clojure lisp, I'd be happy to help just not too sure where to start.

**Comment by patrickaroo** [comment]
This would be so great... neotree is all I need, not dired, but I do need the ability to peep at files. I feel lame not working on this myself, but my skills just aren't there yet.

**Comment by mijoharas** [comment]
Hey, essentially, I have done absolutely nothing about this. In spacemacs you can use `helm-find-files` (`SPC f f`) and then when you hit tab it'll preview the result, which is what I've been using.

Bringing this feature to `neotree` is something that would be nice, I'm not sure if I've got the time though. @jaypei's suggestion sounds like a nice way to go about it in practice.

If I have the time to hack around on this I'll post here, otherwise, I'm afraid don't expect much. Happy to help if needed though.

**Comment by mijoharas** [comment]
Also, @arronmabrey as I'm looking at this, I see a quick-look functionality. If you hit `'` (apostrophe) in spacemacs it will previiew the file.

**Comment by mijoharas** [comment]
@jaypei So I've got a mostly functional implementation for this, but I noticed that you don't use `dash.el`, I'd like to use a filter function, what should I use instead?
