### ISSUE TITLE
Update neotree working dir if called again

### ISSUE THREAD

**Issue by Ganneff** [jaypei/emacs-neotree#47]
Hi,

if i open neotree from some buffer for the first time, it shows the directory that fits to the buffer. Fine.
If i now switch to another buffer for a file in some other dir and get neotree up again, it shows the old directory instead of updating.

Killing the neotree buffer instead of "toggling" it helps, then it ends in the right place.
But it would be nice if it (probably customizable) could just always refresh the dir on toggle.

Thanks,
Joerg

**Comment by ashnur** [comment]
Hi, I am curious if I can achieve the same without closing/reopening neotree? Like when switching buffers.

**Comment by jaypei** [comment]
Hi ashnur,

You can find a hook or advice, and invoke `neotree-find`.
For examples, `select-window` or `buffer-list-update-hook`.
But the problem is that redefine these events is easy to make a infinite-loop,
so you might need define some state variables.

Jaypei

**Comment by ashnur** [comment]
Thank you.

**Comment by jaypei** [comment]
You're welcome, it also suggests that NeoTree is not flexible enough, I will try to make things simple. :)
