### ISSUE TITLE
"Up a dir"

### ISSUE THREAD

**Issue by Ganneff** [jaypei/emacs-neotree#48]
Hi,

and it would be nice to have ".." bound to a keybinding in neotree, that is, pressing (say) ^ goes up a dir. Without the user having to scroll to and "selecting" the .. entry.

Thanks,
 Joerg

**Comment by cosven** [comment]
In my opinion, just show `..` in neotree GUI. So we can go to the parent dir with `C-c C-c`.

![image](https://cloud.githubusercontent.com/assets/4962134/10183829/e381e230-6766-11e5-8c6b-dceb8074e597.png)

**Comment by cosven** [comment]
This [doc](http://www.emacswiki.org/emacs/NeoTre) do not show the usage about the shortcut `U`.
