### ISSUE TITLE
Ability to filter out certain filenames (e.g. *.pyc, *.tmp.)

### ISSUE THREAD

**Issue by razzmatazz** [jaypei/emacs-neotree#53]
It would be nice to be able to filter-out files by filename.

Something like defined here: https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el#L45 but not a constant. (I don't know that much of emacs/elisp -- that might be overridable somehow in .emacs, right?)

**Comment by expez** [comment]
Fantastic! :+1:

**Comment by jaypei** [comment]
@razzmatazz @expez 
Thanks for your ideas -- making NeoTree more awesome.


Jaypei

**Comment by mmcnl** [comment]
Hi, thanks for your work on this project!

I wonder if there's any way to blacklist certain files (e.g. `.DS_Store`) from ever being displayed even when neotree is in the mode where it's showing other hidden files (e.g. `.gitignore`). Neotree's current behavior is to either hide files (using `neo-hidden-regexp-list`) or show all files without exception.

**Comment by andreis** [comment]
Agreeing with @mmcnl, hiding files from `.[X]ignore` would be a way better default IMHO. The default of hiding dotfiles is very annoying (if you toggle H you get `*~` too, and all sorts of files).
