### ISSUE TITLE
fixed - small - independent - font-size ?

### ISSUE THREAD

**Issue by ahmadseleem** [jaypei/emacs-neotree#55]
I really like to this to go to the next level Visually:

How about trying to make it like the sidebar of textmate; where the list of the file have their own
font-size and the font is small because it helps make the file names less trimmed.

What you guys think ?

**Comment by jupl** [comment]
I tried it and I get inconsistent line heights. Root-level directories are good in height but subdirectories and files at all levels have a significant line height.

![screenshot](https://cloud.githubusercontent.com/assets/2065876/5714529/27a18e92-9a90-11e4-8245-92b268d68d0d.png)

**Comment by jaypei** [comment]
You can try to remove the custom font style.
Does anyone else have this problem?

**Comment by jupl** [comment]
Stripped out customizations and still get this.

![ss](https://cloud.githubusercontent.com/assets/2065876/5790676/f95f5ed2-9e69-11e4-8bed-1fcfa6524abf.png)

**Comment by jaypei** [comment]
Hi jupl,

Try the following steps:

1. Switch to neotree-buffer
2. M-x mark-whole-buffer RET
3. M-x kill-ring-save
4. Switch to another buffer and use C-y to paste

Is the inconsistent line heights in the new buffer?


Jaypei

**Comment by jupl** [comment]
No there is no inconsistency. I did notice that it looks like some places does not have the new font size. It looks like the default font size is used when I hover over some areas.

![1](https://cloud.githubusercontent.com/assets/2065876/6134462/371caaac-b127-11e4-97c6-03fb3fcbf9d2.png)

![2](https://cloud.githubusercontent.com/assets/2065876/6134465/40141a0a-b127-11e4-8f1d-ee813c6af4f3.png)

![3](https://cloud.githubusercontent.com/assets/2065876/6134469/4464d45a-b127-11e4-992a-22bcbca2a99b.png)

**Comment by jaypei** [comment]
Hi jupl,

Can you give me the definition of these faces?
* neo-expand-btn-face
* neo-dir-link-face

Jay
