### ISSUE TITLE
Colorscheme weirdness with monokai

### ISSUE THREAD

**Issue by rphillips** [jaypei/emacs-neotree#56]
I'm not sure why the file names are showing up strangely here... I'm using the stock monakai theme.

![screen shot 2014-11-09 at 2 06 49 pm](https://cloud.githubusercontent.com/assets/1963/4968810/f7d915fc-684b-11e4-8884-de37c36b7f77.png)

**Comment by amirrajan** [comment]
How would I go about over riding the color scheme?

**Comment by amirrajan** [comment]
Added this to my init.el

<pre>
(custom-set-faces
 '(col-highlight ((t (:background "color-233"))))
 '(hl-line ((t (:background "color-233"))))
 '(lazy-highlight ((t (:background "black" :foreground "white" :underline t))))
 '(neo-dir-link-face ((t (:foreground "cyan"))))
 '(neo-file-link-face ((t (:foreground "white")))))
(custom-set-variables)
</pre>

**Comment by SDLyu** [comment]
@amirrajan Good solution!

**Comment by nexayq** [comment]
@amirrajan Thanks, great solution
