### ISSUE TITLE
delete-other-window causes error with popwin and ido

### ISSUE THREAD

**Issue by kaushalmodi** [jaypei/emacs-neotree#58]
I have to set `neo-persist-show` to `nil` to disable `(defadvice delete-other-windows ..`.
I have ido and popwin enabled.

With that configuration, when I hit <kbd>TAB</kbd> in the minibuffer, `ido-complete` is called, which in turn calls `ido-completion-help` if there are multiple completion items to be shown.

That triggers popwin, which calls `delete-other-windows` and there, if the defadvice set in this package is active (if `neo-persist-show` is `t`), then I get the elisp error `"Attempt to delete minibuffer or sole ordinary window"`.  

Can you please fix the defadvice so that it doesn't try to delete the minibuffer window?

**Comment by kaushalmodi** [comment]
Thanks @syl20bnr. This issue is fixed for me.

**Comment by kaushalmodi** [comment]
@syl20bnr @jaypei

This issue needs to be reopened.. the problem is still there.

I can't see the completions when I do `C-x 8 RET *rect* TAB`

The issue is fixed with this hack suggested before:

<pre>
    (setq-default neo-persist-show t)
    (when neo-persist-show
      (add-hook 'popwin:before-popup-hook
                (lambda () (setq neo-persist-show nil)))
      (add-hook 'popwin:after-popup-hook
                (lambda () (setq neo-persist-show t))))
</pre>

**Comment by jaypei** [comment]
Hi kaushalmodi,

Can you provide the function name?
`C-h k C-x 8 RET`

Thanks.
Jaypei

**Comment by kaushalmodi** [comment]
But default, `C-x 8 RET` is bound to `insert-char`.

**Comment by jaypei** [comment]
Hi kaushalmodi,

Recently, I reconstructed the popwin advice functions, and I have passed the test,
is your problem still there?

**Comment by kaushalmodi** [comment]
Thanks! This issue is fixed now.

FWIW, I now use `shackle` instead of `popwin` and `ivy` instead of `ido`. I temporarily switched back to `popwin` and `ido` to test this bug fix.
