### ISSUE TITLE
Hide neotree window after open a file

### ISSUE THREAD

**Issue by weih** [jaypei/emacs-neotree#77]
Can we do this in Neotree? I think It's the default behavior in NerdTree.vim, have a option to toggle this feature should be great.

**Comment by jaypei** [comment]
Hi weih,

I think this is reasonable, add an option to support it,
by default it is disabled.

This issue reminded me that I should add a hook "neotree-enter-hook",
and you can hacking some code like this

```emacs
(add-hook 'neo-enter-hook
          (lambda (t) (if (equal t 'file)
                          (neotree-hide))))
```

**Comment by weih** [comment]
@jaypei That's great. :+1:

**Comment by rzetterberg** [comment]
I used this naive solution in my .emacs: 

```elisp
(defun neo-open-file-hide (full-path &optional arg)
  "Open a file node and hides tree."
  (neo-global--select-mru-window arg)
  (find-file full-path)
  (neotree-hide))

(defun neotree-enter-hide (&optional arg)
  "Enters file and hides neotree directly"
  (interactive "P")
  (neo-buffer--execute arg 'neo-open-file-hide 'neo-open-dir))
```

Then I just rebind `RET` to execute `neotree-enter-hide` instead of `neotree-enter`.

Maybe someone else finds this useful before a hook for enter is added upstream :)

**Comment by mmcnl** [comment]
@rzetterberg Thanks for that. Would you mind sharing the commands you're using to rebind `RET` while in the neotree-mode?

**Comment by rzetterberg** [comment]
@mmcnl Sure thing!

I'm using `evil-mode` so my keybindings are set to work in normal mode inside neotree:

```elisp
(add-hook
 'neotree-mode-hook
 (lambda ()
   (define-key evil-normal-state-local-map (kbd "RET") 'neotree-enter-hide)))
```

If you are not using `evil-mode` this should work:

```elisp
(add-hook
 'neotree-mode-hook
 (lambda ()
   (define-key neotree-mode-map (kbd "RET") 'neotree-enter-hide)))
```

**Comment by jaypei** [comment]
NeoTree now has a new hooks "neo-enter-hook", I think it is more suitable for you.
Have these solutions already solved your issue?

**Comment by mmcnl** [comment]
Thanks @rzetterberg for pointing me in a good direction with the keymapping. I'm using spacemacs so I ended up just extending it's hooks to run my two little added functions:
```lisp
(defun custom-neotree-enter-hide ()
  (interactive)
  (neotree-enter)
  (neotree-hide)
  )

(defun custom-neotree-peek ()
  (interactive)
  (neotree-enter)
  (select-window-0)
  )

(defadvice spacemacs//neotree-key-bindings (after add-custom-keybindings activate)
  "add keybindings for enter-hide and peek functions"
  (define-key evil-motion-state-local-map (kbd "RET") 'custom-neotree-enter-hide)
  (define-key evil-motion-state-local-map (kbd "TAB") 'custom-neotree-peek)
  )
```
@jaypei Thanks for following up on this. I could possible use the `neo-enter-hook` for the `enter-hide` function, but maybe not so easily for `peek`.

**Comment by jaypei** [comment]
Yes, the `peek` looks more suitable  :)

**Comment by mstorus** [comment]
Hi,
Since this issue a little old, what is the current best way to hide the neotree window after opening a file? Is there a customizable option now?

**Comment by BadDecisionsAlex** [comment]
> Thanks @rzetterberg for pointing me in a good direction with the keymapping. I'm using spacemacs so I ended up just extending its hooks to run my two little added functions:
> 
> ```lisp
> (defun custom-neotree-enter-hide ()
>   (interactive)
>   (neotree-enter)
>   (neotree-hide)
>   )
> 
> (defun custom-neotree-peek ()
>   (interactive)
>   (neotree-enter)
>   (select-window-0)
>   )
> 
> (defadvice spacemacs//neotree-key-bindings (after add-custom-keybindings activate)
>   "add keybindings for enter-hide and peek functions"
>   (define-key evil-motion-state-local-map (kbd "RET") 'custom-neotree-enter-hide)
>   (define-key evil-motion-state-local-map (kbd "TAB") 'custom-neotree-peek)
>   )
> ```
> 
> @jaypei Thanks for following up on this. I could maybe use the `neo-enter-hook` for the `enter-hide` function, but maybe not so easily for `peek`.

Did you add this to `dotspacemacs/user-config`?
