### ISSUE TITLE
Some suggesstion for enhancement

### ISSUE THREAD

**Issue by kuanyui** [jaypei/emacs-neotree#81]
I think some small functions would make Neotree more convenient for using:

1. `find-file` at the node. That is, `find-file` with the var `default-directory` set to current node, which let user be able to open the directory node with `dired-mode` directly, or open a new file under the directory node. (I have to say `C-c C-n` is too inconvenient and against instinct. How about bind `+` to `mkdir` with the current node's path set as `default-directory`?)
2. hide unnecessary items (e.g. `#*#`, `*~`)

**Comment by jaypei** [comment]
I agree with all that, thanks.

**Comment by f0086** [comment]
Hiding unnecessary items already on #53, and #82.
