### ISSUE TITLE
Hide certain file extensions

### ISSUE THREAD

**Issue by f0086** [jaypei/emacs-neotree#82]
It would be great if there where a blacklist of extensions (configured per customize) which will not be visible in the tree. Files I am thinking of: 

* *.elc
* Dotfiles
* *.o
* *.zip

**Comment by f0086** [comment]
Sorry for the duplicate issue. There is more on #81 and #53

**Comment by jaypei** [comment]
It can be customized now, so I close this issue.
Thanks.

Jay
