### ISSUE TITLE
Automatically open single child folder

### ISSUE THREAD

**Issue by 4lex1v** [jaypei/emacs-neotree#85]
Probably it's already been implemented and i don't know of it, but i'd like to see the behaviour like github has, i.e when i have structure `a/b/c/d/file`, and there are no other folders/files in `a`,`b`,`c`, neotree would automatically open these folders. I've tried to modify `neotree-enter` function, but couldn't get it working.

**Comment by jaypei** [comment]
Hi Ivanov,
 
NeoTree dose not implement this feature yet.
I think it need to modify neo-buffer--insert-tree and neo-buffer--insert-dir-entry.

Jaypei

**Comment by jaypei** [comment]
Merge to #147 .
