### ISSUE TITLE
Customize neotree placement

### ISSUE THREAD

**Issue by dblezek** [jaypei/emacs-neotree#87]
Typically, I reserve the left side of buffers for text editing, and place less important things on the right hand side.  Is there a way to tell neotree to open on the right instead of the left?  Could not find any customization options to accomplish this.

**Comment by jaypei** [comment]
Hi dblezek,

So far it has not, but this is a good idea.

Jaypei

**Comment by jamieorc** [comment]
I want this as well. I find trees to the left quite distracting. Interestingly another user reported that his *always* opens on the right, which is where I want it. Curious how that is happening: https://github.com/jaypei/emacs-neotree/issues/54

**Comment by jamieorc** [comment]
@dblezek I just managed to use transpose-frame as a work-around. flop-frame moved neotree to right side, leaving it on left as well, but I closed that and now have it on the right. http://www.emacswiki.org/emacs/TransposeFrame

**Comment by jamieorc** [comment]
My work-around doesn't actually work. When I click on a file to open it, neotree opens itself on the left again, so the pane is duplicated on the left and right sides. D'OH!

**Comment by istinspring** [comment]
+1 same. I use emacs prelude and after update packages neo-tree started to appear on the right side instead on left.

**Comment by jaypei** [comment]
Hi all,

NeoTree has already supported to open on the right side.
You can do this by using the option `neo-window-position`.

Jay

**Comment by AmetAlvirde** [comment]
@jaypei tried `(neo-window-position 'right)` because that seemed ok, but it isn't and I can't find any documentation related to that variable. Can you be more specific about how to use it? Thank you so much. :)
