### ISSUE TITLE
Hide certain file types

### ISSUE THREAD

**Issue by gopar** [jaypei/emacs-neotree#90]
This is a feature request rather than a bug. It would be nice if we could customize neotree to hide certain file extensions, such as **.class** for java or **.pyc** for python, etc. It gets cluttered when there are unwanted files.

Update: Just realized neotree hides *pyc* files automatically.  Should of checked that first :p

**Comment by gopar** [comment]
Did not realize I was able to customize what type of files to hide through the use of **M-x Customize** and then setting the values there.

**Comment by byxor** [comment]
Can you explain how you achieved this? I'm not sure what to do from the `Customize` buffer.

**Comment by palikar** [comment]
@byxor  You should open the `Customize` buffer of the group `Neotree`. There there is the setting `Neo Hidden Regexp List`. In it you can add entries and the matched files with any of the entries will be hidden in Neotree.

**Comment by byxor** [comment]
It works. Thanks. :smile:
