### ISSUE TITLE
File names not visible. Need to be able to change text color.

### ISSUE THREAD

**Issue by ksafford** [jaypei/emacs-neotree#91]
![screen shot 2015-03-16 at 3 03 53 pm](https://cloud.githubusercontent.com/assets/1257916/6675536/1624a2cc-cbef-11e4-8f6b-7132cec40c66.png)

**Comment by ksafford** [comment]
C-u C-x = will give you info about the text under the point. This is great! It displays the face for the character and you can navigate to that face's configuration. From there you can navigate to customize_this_face. Problem solved.

**Comment by xdream86** [comment]
thanks
