### ISSUE TITLE
Regression: clicking neotree directories does not open

### ISSUE THREAD

**Issue by pandeiro** [jaypei/emacs-neotree#94]
In the latest version on Melpa (`neotree-20150322.518`), clicking on directories in neotree does not expand/contract them, but produces the error `Buffer is read-only: #<buffer  *NeoTree*>`.

(Expanding directories via <Enter> on the keyboard still works as usual.)

**Comment by stormpat** [comment]
+1

**Comment by jaypei** [comment]
Thanks!
