### ISSUE TITLE
Feature: Allow moving of files (and directories)

### ISSUE THREAD

**Issue by mijoharas** [jaypei/emacs-neotree#96]
I tend to use neotree for most of my file navigation purposes now. It would be good if I were able to move files (and folders) from within neotree.

**Comment by jaypei** [comment]
Hi mijoharas,

You can try `neotree-rename-node` (C-c C-r).

Jaypei

**Comment by mijoharas** [comment]
just realised I hadn't closed this, thanks. :smile:

**Comment by byxor** [comment]
Thanks, I was wondering how to do this.

**Comment by hraban** [comment]
When I do this, I have to retype the full filename every time. This makes sense for _renaming_, but less so for _moving_ a file. If I just enter `/path/to/new/dir/` (with terminating `/`), I get:

```
Empty file name
```

Annoyingly, sometimes this does in fact work. But most times, I get that error.

Is this intended behaviour?

**Comment by arvydasg** [comment]
@hraban Did you figure it out? I am tired of _retyping_ the whole file name when changing it's directory.

**Comment by hraban** [comment]
No I ended up going with this snippet https://lists.gnu.org/archive/html/emacs-devel/2018-05/msg00233.html from emacs-devel. I retrained myself not to use neotree for renames. It's a workaround so if you ever find a better solution, keep me posted.

**Comment by valer-cara** [comment]
Same frustration, ended up using built-in `dired` which is pretty snappy, key-wise
1. `C-x C-j` opens dired at current file;
2. `R` rename file to which you can supply the target dir only, no need to type the original filename too;
3. `q` to get rid of it and back to your buffer (in its new location all right)
