### ISSUE TITLE
Which font are you using in the screenshot, by the way? 

### ISSUE THREAD

**Issue by ReneFroger** [jaypei/emacs-neotree#97]
I like the font in the screenshot: 

![](https://raw.githubusercontent.com/wiki/jaypei/emacs-neotree/imgs/neotree-1.png)

Could you tell me which font you use? I looked into your Emacs configuration, but the lines: 

    (setq cn-name (if *is-a-mac* "STHeiti" "STHeiti"))
    (setq en-name (if *is-a-mac* "Inconsolata" "Ubuntu Mono"))

Don't correspond with the font used in the screenshot. 

Thanks in advance for your reply.

**Comment by jaypei** [comment]
Fantasque Sans Mono  :)

**Comment by ReneFroger** [comment]
Sorry for the belated response. But thanks for your reply, it's appreciated!

**Comment by jaypei** [comment]
You are welcome :)

**Comment by RnMss** [comment]
How did you fit that light-on-dark font antialiasing on OS X? (I thought it is impossible.)

**Comment by RnMss** [comment]
Oh I know, you simply shut down subpixel antialias...
