### ISSUE TITLE
Unable to Open File / Toggle Dir

### ISSUE THREAD

**Issue by jupl** [jaypei/emacs-neotree#98]
I had to do a clean install of my config and installed latest from MELPA. I am unable to open a file or toggle a directory when hitting `RET`.

**Comment by jaypei** [comment]
Hi jupl,

What version of emacs are you using?
Please give me the output of this expression:
(print neotree-mode-map)

Jaypei

**Comment by jupl** [comment]
Tried it with Emacs 24.4 in terminal and GUI mode, as well as Emacs 24.5-rc1-mac-5.6 and all have the same issue. 

After investigating it appears that it no longer works when Evil is loaded. I can confirm it was not a change on Evil's part because I replaced the Neotree's code with with that of the latest commit before `e45f3cab4d` and could not replicate the issue with the most recent version of Evil. When I changed it back to the latest commit `e45f3cab4d` then the keys no longer work. Mouse clicks do work though.

```
(keymap (3 keymap (18 . neotree-rename-node) (4 . neotree-delete-node) (14 . neotree-create-node) (3 . neotree-change-root) (6 . find-file-other-window)) (24 keymap (51 . neotree-empty-fn) (50 . neotree-empty-fn) (49 . neotree-empty-fn) (6 . find-file-other-window)) (115 . neotree-select-next-sibling-node) (83 . neotree-select-previous-sibling-node) (72 . neotree-hidden-file-toggle) (68 . neotree-select-down-node) (85 . neotree-select-up-node) (65 . neotree-stretch-toggle) (14 . neotree-next-line) (110 . neotree-next-line) (16 . neotree-previous-line) (112 . neotree-previous-line) (113 . neotree-hide) (103 . neotree-refresh) (45 lambda (&optional arg) (interactive "P") (neo-global--select-window) (neo-buffer--executor arg (quote neo-open-file-horizontal-split) (function (lambda (&rest _))))) (124 lambda (&optional arg) (interactive "P") (neo-global--select-window) (neo-buffer--executor arg (quote neo-open-file-vertical-split) (function (lambda (&rest _))))) (13 lambda (&optional arg) (interactive "P") (neo-global--select-window) (neo-buffer--executor arg (quote neo-open-file) (quote neo-open-dir))) (9 lambda (&optional arg) (interactive "P") (neo-global--select-window) (neo-buffer--executor arg (function (lambda (&rest _))) (quote neo-open-dir))))
```

**Comment by jaypei** [comment]
This code should be helpful

```
(add-hook 'neotree-mode-hook
          (lambda ()
            (define-key evil-normal-state-local-map (kbd "TAB") 'neotree-enter)
            (define-key evil-normal-state-local-map (kbd "SPC") 'neotree-enter)
            (define-key evil-normal-state-local-map (kbd "q") 'neotree-hide)
            (define-key evil-normal-state-local-map (kbd "RET") 'neotree-enter)))
```

**Comment by svalaskevicius** [comment]
I've got the same problem, and the error it shows is that `neo-buffer--execute` is not defined (which looks to be true by searching in the repo)

**Comment by jvillasante** [comment]
Same problem here, after updating to latest commit when I try to open/toggle a file/folder with RET I get the error "Symbol's function definition is void: neo-buffer--execute"

**Comment by jaypei** [comment]
Thanks, fixed.
